### ISSUE TITLE
A15B1 broke zygisk completely

### ISSUE THREAD

**Issue by TQMatvey** [Dr-TSNG/ZygiskOnKernelSU#101]
after flashing Android 15 Beta 1 users have encountered that Magisk's Zygisk/ZygiskNext stopped working and just crashes upon booting... 
[Stop inject zygote due to crash. Root: Magisk]

here is a logcat i captured while booting
[deadzygisk.txt](https://github.com/Dr-TSNG/ZygiskNext/files/14953852/deadzygisk.txt)
hope this helps. Thanks for you Work

**Comment by 5ec1cff** [comment]
![image](https://github.com/Dr-TSNG/ZygiskNext/assets/56485584/5c2299a7-5192-4cda-b26f-40e74fb42c74)


It works for me
