### ISSUE TITLE
Zygisk Next stopped due to Crash

### ISSUE THREAD

**Issue by xxxsskxxx** [Dr-TSNG/ZygiskOnKernelSU#102]
I updated to the lineageOS latest nightly today https://download.lineageos.org/devices/oriole/changes (LINEAGE-21.0-20240415-NIGHTLY-ORIOLE-SIGNED.ZIP)

Pixel 6
LineageOS 21 Nightly (was working before 15/04/24 build)
KernelSU 0.9.2 (11628)
ZygiskNext (1.0.4)

And now ZygiskNext complains of an error

[KernelSU_bugreport_2024-04-15_13_53.tar.gz](https://github.com/Dr-TSNG/ZygiskNext/files/14979240/KernelSU_bugreport_2024-04-15_13_53.tar.gz)
![529c5ffb-a47d-416e-b19c-91c3a26f0616](https://github.com/Dr-TSNG/ZygiskNext/assets/96975040/cb791a71-f4e7-4e57-a0ac-6b32c437f2a5)
![b52fde1a-4f67-4449-bc78-2d9475c75e36](https://github.com/Dr-TSNG/ZygiskNext/assets/96975040/b478985b-9ca9-46e6-a4ae-3fe26826f497)
![62b21756-eac7-45b7-98a5-fb581e3380ff](https://github.com/Dr-TSNG/ZygiskNext/assets/96975040/ee9bc4fa-f229-4032-aab9-474d468b0bb2)

Logs and screenshots attached.

**Comment by 5ec1cff** [comment]
use newer lsposed

**Comment by xxxsskxxx** [comment]
Shouldnt ZygiskNext work without Lsposed, as my PIF module also fails passing integrity now..?

**Comment by 5ec1cff** [comment]
lsposed crashes your system and zygisk next stop injecting
