### ISSUE TITLE
Android 15 Beta 1.1 doesnt work

### ISSUE THREAD

**Issue by lssong99** [Dr-TSNG/ZygiskOnKernelSU#103]
[verbose_2024-04-23T231019.574069.log](https://github.com/Dr-TSNG/ZygiskNext/files/15079171/verbose_2024-04-23T231019.574069.log)
Zygisk Next 1.0.4 doesn't work on A15B1.1. on Magisk Modles screen "Stop inject zygote due to crash. Root: Magisk" is displayed. 1.0.4 works on A14QBR2. Pixel 8 Pro

Attached is the log. (please let me know if this is correct log or not)

Okay. It's caused by Zygisk - LSPosed v1.9.2 (7038)....

**Comment by 5ec1cff** [comment]
Your lsposed doesn't work on A15B1.1, not Zygisk Next
