### ISSUE TITLE
Zygisk Next not working on android 13

### ISSUE THREAD

**Issue by GoofieDragon** [Dr-TSNG/ZygiskOnKernelSU#104]
I flashed the latest zygisk next v1.0.4 through ksu which is also updated to the latest v0.9.3-3 but the zygisk next is showing greyed out in the module list and doesn't work. Using it for Zygisk Lspoed v1.9.2 which is also greyed out and doesn't work ( I am on Evolution X android 13 rom and my device is Redmi K20 Pro / Xiaomi Redmi Mi9T pro ).

**Comment by 5ec1cff** [comment]
no logs no fix
