### ISSUE TITLE
browsers (Chrome, Android System WebView) will not start after enable "enforce denylist" 

### ISSUE THREAD

**Issue by AZVW2** [Dr-TSNG/ZygiskOnKernelSU#105]
browsers (Chrome, Android System WebView) will not start after enable "enforce denylist"....... if close Zygisk Next WebUI after enable "enforce denylist", the WebUI will not start again, unless reinstall Zygisk Next

**Comment by Webpage-gh** [comment]
Can you provide crash logs for Chrome? [AppErrorsTracking](https://github.com/KitsunePie/AppErrorsTracking) is a Xposed module  to capture crashes. Known to use the font module and Zygisk 1.0.4 will cause this problem, and the blacklist mode of Zygisk version 1.0.3 can temporarily solve this problem.
