### ISSUE TITLE
在没有更新xposed模块和kernelsu模块的情况下，zygisk next有时能正常启动，有时又会crash。

### ISSUE THREAD

**Issue by MobInfinity** [Dr-TSNG/ZygiskOnKernelSU#106]
在没有更新xposed模块和kernelsu模块的情况下，zygisk next有时能正常启动，有时又会crash。
能帮忙看看是什么原因导致的吗，我自己实在是排查不出来了。
[KernelSU_bugreport_2024-04-28_08_36.tar.gz](https://github.com/Dr-TSNG/ZygiskNext/files/15140403/KernelSU_bugreport_2024-04-28_08_36.tar.gz)

**Comment by 5ec1cff** [comment]
lsp 问题

**Comment by MobInfinity** [comment]
> lsp 问题

好的明白了，谢谢你的帮助。
