### ISSUE TITLE
Device detect Zygisk

### ISSUE THREAD

**Issue by hideandseekstheorder** [Dr-TSNG/ZygiskOnKernelSU#107]
When enable Enforce DenyList device not detect zygisk but module zygisk not active, but if i am disable Enforce DenyList, device detect zygisk.

**Comment by hideandseekstheorder** [comment]
![Screenshot_2024-04-30-04-23-24-375_io github rabahx securify](https://github.com/Dr-TSNG/ZygiskNext/assets/24226435/4c57192d-e191-4b01-a0bb-1eb80f5f98a1)
![Screenshot_2024-04-30-04-23-20-738_io github rabahx securify](https://github.com/Dr-TSNG/ZygiskNext/assets/24226435/4323a336-6f33-4e55-bc09-3abb854a5289)

**Comment by Webpage-gh** [comment]
same question.
