### ISSUE TITLE
LSPosed not working after enabling Deny list

### ISSUE THREAD

**Issue by Webpage-gh** [Dr-TSNG/ZygiskOnKernelSU#109]
<details><summary>中文议题</summary>

## 问题描述
在将 ZygiskNext 从版本 1.0.3 升级到 1.0.4 后，我遇到了 Zygisk 模块无法注入到应用的问题。以下是问题的详细描述：

### 版本信息
- ZygiskNext: ![ZygiskNext 版本信息](https://github.com/Dr-TSNG/ZygiskNext/assets/70434775/076e5ff5-45b5-46a7-937a-887f2c5a0a3b)
- Apatch: ![Apatch 版本信息](https://github.com/Dr-TSNG/ZygiskNext/assets/70434775/dde25ea0-9d7c-4b31-a1d4-866969a40857)

### 问题描述
- 在 1.0.4 版本中，"Enforce Denylist" 模式与 1.0.3 版本的白名单模式行为不同，导致所有 Zygisk 模块无法注入到应用程序中，影响了 Xposed 模块的工作，Sui 的设置界面也无法正常打开。

### 复现步骤
1. 安装 APatch，ZygiskNext，LSPosed。
2. 在拨号盘输入 *#*#5776733#*#*（数字对应键盘中 LSPOSED 字母）。

### 预期行为
- LSPosed 可以打开，说明拨号盘被 LSPosed 注入。

### 实际行为
- LSPosed 没有打开。

### 期望的解决方案
- 希望开发者能够调查 1.0.4 版本中白名单模式的行为变化，并进行修复，以允许 Zygisk 模块正常注入到应用程序中。

### 附加信息
- 在强制执行拒绝名单（Enforce Denylist）时，安装字体模块后 Chrome 会崩溃。崩溃日志可以在提供的 [日志压缩包](https://github.com/Dr-TSNG/ZygiskNext/files/15208179/LSP-and-Apatch-log.zip) 中的 `tombstones/tombstone_00` 路径下找到。压缩包中包含了由 Apatch 和 LSPosed 生成的日志。

感谢您的时间和帮助，期待您的回复。
</details>

## Issue Description
After upgrading ZygiskNext from version 1.0.3 to 1.0.4, I encountered an issue where Zygisk modules could not be injected into applications. Here is a detailed description of the problem:

### Version Information
- ZygiskNext: ![ZygiskNext Version Info](https://github.com/Dr-TSNG/ZygiskNext/assets/70434775/076e5ff5-45b5-46a7-937a-887f2c5a0a3b)
- Apatch: ![Apatch Version Info](https://github.com/Dr-TSNG/ZygiskNext/assets/70434775/dde25ea0-9d7c-4b31-a1d4-866969a40857)

### Problem Description
- In version 1.0.4, the "Enforce Denylist" mode behaves differently from the whitelist mode in version 1.0.3, resulting in Zygisk modules being unable to inject into applications. This affects the functionality of Xposed modules, and the Sui settings interface cannot be opened normally.

### Repro Steps
1. Install APatch, ZygiskNext, LSPosed.
2. Enter *#*#5776733#*#* in the dial pad (numbers correspond to the letters of LSPOSED on the keyboard).

### Expected Behavior
- LSPosed should open, indicating that the dial pad has been injected by LSPosed.

### Actual Behavior
- LSPosed does not open.

### Desired Solution
- I hope developers can investigate the behavior change in the whitelist mode of version 1.0.4 and provide a fix to allow Zygisk modules to be injected normally into applications.

### Additional Information
- When enforcing the denylist, installing a font module causes Chrome to crash. The crash log can be found in the provided [log archive](https://github.com/Dr-TSNG/ZygiskNext/files/15208179/LSP-and-Apatch-log.zip) at the path `tombstones/tombstone_00`. The archive contains logs generated by Apatch and LSPosed.

Thank you for your time and assistance. I look forward to your response.

**Comment by Dr-TSNG** [comment]
预期行为
