### ISSUE TITLE
lsposed未生效

### ISSUE THREAD

**Issue by Doddddd** [Dr-TSNG/ZygiskOnKernelSU#11]
设备：Windows Subsystem For Android
内核：kernel-WSA-x86_64-5.10.117.2 (https://github.com/tiann/KernelSU/releases/tag/v0.4.0)
kernelsu版本: 10672
管理器版本: 10672
Zygisk-on-KernelSU版本：v4-0.6.2-66-release
lsposed版本：v1.8.6-6712-zygisk-release
log：
[20230304043148.log](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/10887493/20230304043148.log)

**Comment by callng** [comment]
好像目前不兼容WSA 我的WSA版本2301.40000.7.0 重启后ksu的超级用户开关会被重置。

**Comment by callng** [comment]
> 好像目前不兼容WSA 我的WSA版本2301.40000.7.0 重启后ksu的超级用户开关会被重置。

这应该是ksu的兼容性问题

**Comment by SoDebug** [comment]
> 内核版本：5.10.101 管理器版本：0.5.4 10802 api 33 请问下师傅为啥我这个没法装最新的这个模块，说我的kernel版本老旧

编译内核时，KernelSu是拉取的最新代码吗？

**Comment by kerna60** [comment]
我的wsa都用不了ksu你竟然能用，自己跑的吗

**Comment by tiann** [comment]
https://github.com/tiann/KernelSU/commit/f4d2b0feabce41ccdb84adfa5c59532e8939267e
此问题 ksu 已修复
