### ISSUE TITLE
安装1.0.4版本，点击通知的lsposed无反应

### ISSUE THREAD

**Issue by kenny68** [Dr-TSNG/ZygiskOnKernelSU#111]
安装1.0.4版本，点击通知栏的lsposed无反应，打不开lsposed管理器，无法创建快捷方式

1、机型：pixel2+Android11（RP1A.201005.004）
2、打开enforce denylist mode
3、尝试1.0.2版本，可以打开lsposed管理器

**Comment by 5ec1cff** [comment]
关掉
