### ISSUE TITLE
What does mazoku do?

### ISSUE THREAD

**Issue by miracoco** [Dr-TSNG/ZygiskOnKernelSU#112]

**Comment by u9521** [comment]
The mazoku file contains a 64-byte Ed25519 digital signature in its initial segment, followed by a 32-byte public key (presumably corresponding to the signature verification key). This structure mirrors the 96-byte composition observed in the machikado.xx file, as implemented in [commit 28f77fa](https://github.com/Dr-TSNG/ZygiskNext/commit/28f77fa5e21a26949eff533f108ca38c295c5b10).

The signature generation process for machikado.xx incorporates the mazoku file as one of input. 
By the way, the maintainer really loves _Machikado Mazoku_.
