### ISSUE TITLE
您好 我想咨询一个问题

### ISSUE THREAD

**Issue by Moonbow1999** [Dr-TSNG/ZygiskOnKernelSU#115]
我使用的root是kernelsu为了使lsposed生效
我安装了两个模块 zygisk-lsposed和zygisk on kernelsu 可以正常使用lsposed 
现在的问题是 我想安装 zygisk next模块 但是安装完会自动卸载zygisk on kernelsu模块导致lsposed不生效 请问有什么解决方法吗？

**Comment by OrStudio** [comment]
> 我使用的root是kernelsu为了使lsposed生效 我安装了两个模块 zygisk-lsposed和zygisk on kernelsu 可以正常使用lsposed 现在的问题是 我想安装 zygisk next模块 但是安装完会自动卸载zygisk on kernelsu模块导致lsposed不生效 请问有什么解决方法吗？

有沒有可能，zygisk next跟zygisk on kernelsu是一樣的東西

**Comment by PuerNya** [comment]
@Moonbow1999 有没有一种可能，zygisk next 是 zygisk on ksu 的下一个版本，只不过换了名字

**Comment by Moonbow1999** [comment]
谢谢 我才知道 那我又有新的问题 我把zygisk on kernelsu卸载 安装了zygisk next lsposed不生效了怎么办？ > > 我使用的root是kernelsu为了使lsposed生效 我安装了两个模块 zygisk-lsposed和zygisk on kernelsu 可以正常使用lsposed 现在的问题是 我想安装 zygisk next模块 但是安装完会自动卸载zygisk on kernelsu模块导致lsposed不生效 请问有什么解决方法吗？
> 
> 
> 
> 有沒有可能，zygisk next跟zygisk on kernelsu是一樣的東西

**Comment by Moonbow1999** [comment]
谢谢！可以使用了！> > 我使用的root是kernelsu为了使lsposed生效 我安装了两个模块 zygisk-lsposed和zygisk on kernelsu 可以正常使用lsposed 现在的问题是 我想安装 zygisk next模块 但是安装完会自动卸载zygisk on kernelsu模块导致lsposed不生效 请问有什么解决方法吗？
> 
> 
> 
> 有沒有可能，zygisk next跟zygisk on kernelsu是一樣的東西

**Comment by Moonbow1999** [comment]
谢谢！可以使用了！> @Moonbow1999 有没有一种可能，zygisk next 是 zygisk on ksu 的下一个版本，只不过换了名字
