### ISSUE TITLE
KERNEL SU - LSPOSED MODULE

### ISSUE THREAD

**Issue by hideandseekstheorder** [Dr-TSNG/ZygiskOnKernelSU#117]
Enable Enforce Denylist affects the Zygisk Lsposed module !

**Comment by PuerNya** [comment]
@hideandseekstheorder turning on this will cause that injection will be skipped on applications in the black list, so it's expected behavior

**Comment by hideandseekstheorder** [comment]
> @hideandseekstheordermenyalakan ini akan menyebabkan injeksi akan dilewati pada aplikasi dalam daftar hitam, jadi itulah perilaku yang diharapkan



> @hideandseekstheorder turning on this will cause that injection will be skipped on applications in the black list, so it's expected behavior

But I won't be able to blacklist/whitelist my lsposed allocation module

**Comment by PuerNya** [comment]
@hideandseekstheorder not lsposed blacklist but KernelSU blacklist

**Comment by hideandseekstheorder** [comment]
![Screenshot_2024-06-04-03-20-33-517_me weishu kernelsu](https://github.com/Dr-TSNG/ZygiskNext/assets/24226435/e61ce0a0-5d50-41d4-9406-a71975c3538e)
![Screenshot_2024-06-04-03-20-41-534_me weishu kernelsu](https://github.com/Dr-TSNG/ZygiskNext/assets/24226435/597b6fcd-adae-4415-b8d7-e7b2a6ecb2f4)

I am only mounting the root app.

**Comment by PuerNya** [comment]
@hideandseekstheorder mouted app list is the whitelist
