### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by ghost** [Dr-TSNG/ZygiskOnKernelSU#122]
![IMG](https://github.com/Dr-TSNG/ZygiskNext/assets/137070734/2574eab5-bd6f-4471-a471-f16e5a039d5b)

I use the latest kernelsu, if I install the module, the device goes into bootloop, and I have to restart again to be able to log in.  I checked and there weren't any folders and I tried copying manually from the .zip but it still failed.

**Comment by 5ec1cff** [comment]
send logs

**Comment by Kroazer** [comment]
Has same issues
but already fixed, try install v1.0.6-2

**Comment by ghost** [comment]
![Screenshot_20240623-171029~2](https://github.com/Dr-TSNG/ZygiskNext/assets/137070734/20329c53-a6bd-4377-8248-d8b029da3f4f)
![Screenshot_20240623-171118~2](https://github.com/Dr-TSNG/ZygiskNext/assets/137070734/015f6347-4484-4721-9a5c-611b3d087941)
> send logs

how to get logs?

**Comment by ghost** [comment]
> Has same issues but already fixed, try install v1.0.6-2

new version not working.

**Comment by ghost** [comment]
how to fix it?  I really don't know
