### ISSUE TITLE
Clash of clans (crash)

### ISSUE THREAD

**Issue by madyhac** [Dr-TSNG/ZygiskOnKernelSU#124]
When i use force dentist in the module options the game works but i can't use my lsposed modules cuz of that 

Iam using 
Kernel su
Play integrity fix module 
Zgisk next (bruh)
Lsposed on zgisk module 
Yt music revaned module

**Comment by Dr-TSNG** [comment]
What else do u think that option is for?

**Comment by RevealedSoulEven** [comment]
But isn't there a way to add only specific apps in denylist?
