### ISSUE TITLE
Zygisk crashes if LSPosed is enabled

### ISSUE THREAD

**Issue by SkyDontFall** [Dr-TSNG/ZygiskOnKernelSU#125]
### Steps to reproduce/复现步骤
 
     1. Enable LSposed 
     2. Reboot
     3. Zygisk crashes 
 
 ### Expected behaviour/预期行为
 
 Zygisk should work fine
 ### Actual behaviour/实际行为
 
 Zygisk crashes after reboot
 ### KernelSU Module List/KernelSU 模块列表
 
 ```shell
 1. Anti bootloop
 2. Play Integrity Fix
 3. YouTube ReVanced
 4. Zygisk - LSPosed
 5. zygisk-detach
 6. Zygisk - Sui
 7. Zygisk Next
 ```
 
 ### Zygisk Next version/Zygisk Next 版本
 
 Latest ( v1.0.6-2 (317-645a9d7-release))
 ### Android version/Android 版本
 
 14
 ### KernelSU version/KernelSU 版本
 
 11874
 ### Logs/日志
 
 
[KernelSU_bugreport_2024-07-02_11_19.tar.gz](https://github.com/user-attachments/files/16062341/KernelSU_bugreport_2024-07-02_11_19.tar.gz)

**Comment by ShirefReda** [comment]
+1 same proplem exactly just im using magisk

**Comment by ShirefReda** [comment]
UPDATE working rn using this fork : https://github.com/pumPCin/LSPosed

**Comment by pershoot** [comment]
LSPosed mod is working fine on APatch + Zygisk Next (106-2).
7295 (Actions -> CI build): https://github.com/mywalkb/LSPosed_mod/actions
