### ISSUE TITLE
一加ace pro安装后提示崩溃

### ISSUE THREAD

**Issue by fatinghenji** [Dr-TSNG/ZygiskOnKernelSU#13]
在Kernel Su管理器中提示：`zygisk has crashed`
我应该怎样获取并提供错误日志？

**Comment by fatinghenji** [comment]
使用`adb wait-for-device logcat -b all > log.txt`重新抓取log如下：
[log.txt](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/10959426/log.txt)

**Comment by 5ec1cff** [comment]
1+ 用户有问题的试试这个 release：

https://github.com/5ec1cff/ZygiskOnKernelSU/actions/runs/4477116763

**Comment by 5ec1cff** [comment]
已知情报：

1. 都是 zygiskd32 崩溃，backtrace 基本一致：
![image](https://user-images.githubusercontent.com/56485584/226559778-ab201698-ff06-4fa8-a29c-af01223b3d0e.png)
（需要提供 `/apex/com.android.runtime/lib/bionic/libc.so` 以便分析）
2. 都是在 oplus 系统上崩溃
3. debug 版正常而 release 版崩溃
4. [0.4.1](https://github.com/Dr-TSNG/ZygiskOnKernelSU/releases/tag/v4-0.1.0) 前 release 版是正常的

**Comment by Ray93** [comment]
> 1+ 用户有问题的试试这个 release：
> 
> https://github.com/5ec1cff/ZygiskOnKernelSU/actions/runs/4477814421

一加Ace2 这个release版本不崩溃了

**Comment by fatinghenji** [comment]
> 1+ 用户有问题的试试这个 release：
> 
> https://github.com/5ec1cff/ZygiskOnKernelSU/actions/runs/4477814421

一加ace pro该版本release版本正常，未提示崩溃。

**Comment by 5ec1cff** [comment]
> > 1+ 用户有问题的试试这个 release：
> > https://github.com/5ec1cff/ZygiskOnKernelSU/actions/runs/4477814421
> 
> 一加Ace2 这个release版本不崩溃了



> > 1+ 用户有问题的试试这个 release：
> > https://github.com/5ec1cff/ZygiskOnKernelSU/actions/runs/4477814421
> 
> 一加ace pro该版本release版本正常，未提示崩溃。

如果方便的话再看看这个 release ：https://github.com/5ec1cff/ZygiskOnKernelSU/actions/runs/4479712538

如果崩溃，请提供 KernelSU 的 bug report （“分享日志”）。

**Comment by fatinghenji** [comment]
> 

该版本报错崩溃，日志文件提供如下：
[KernelSU_bugreport_2023-03-21_21_54.tar.gz](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11029060/KernelSU_bugreport_2023-03-21_21_54.tar.gz)

**Comment by 5ec1cff** [comment]
bugreport 的日志不全，还是麻烦你们抓个开机的吧（

`adb wait-for-device logcat -b all > log.txt`

**Comment by qi-mooo** [comment]
@5ec1cff https://github.com/5ec1cff/ZygiskOnKernelSU/actions/runs/4477814421 这个好使

**Comment by Dr-TSNG** [comment]
https://github.com/Dr-TSNG/ZygiskOnKernelSU/actions/runs/4480506463
试试

**Comment by Dr-TSNG** [comment]
a6f455218f098f436ff606b4bf5ccfec7578ac90
