### ISSUE TITLE
Failed to inject init

### ISSUE THREAD

**Issue by nsfw404** [Dr-TSNG/ZygiskOnKernelSU#132]
Magisk Canary 27005装zygisk next1.1.0，zygisk不生效 zygisk next提示 [❌ Failed to inject init] Standalone implementation of Zygisk.
[magisk_log_2024-07-25T10.09.32.zip](https://github.com/user-attachments/files/16369759/magisk_log_2024-07-25T10.09.32.zip)

**Comment by 5ec1cff** [comment]
magisk 问题
