### ISSUE TITLE
Black screen while opening zygisk 

### ISSUE THREAD

**Issue by ghost** [Dr-TSNG/ZygiskOnKernelSU#134]
I am getting a black screen while opening zygisk and many apps are disconnected to internet(like banking app, Amazon,Gmail etc) except browser. Idk why it happens.....it randomly crashes. Only way to fix it to reinstall it. I am currently kernel su to use zygisk.

https://github.com/user-attachments/assets/ca78dc40-a11c-4cb1-9e7b-3803abfcaef2

**Comment by 5ec1cff** [comment]
Disable enforce denylist

**Comment by ghost** [comment]
Then banking app won't work. App name - Yono SBI 
It starts crashing.

**Comment by 5ec1cff** [comment]
Use shamiko
