### ISSUE TITLE
[BUG] ZygiskNext Doesn't work on a64 (Binder64)

### ISSUE THREAD

**Issue by toonshouin** [Dr-TSNG/ZygiskOnKernelSU#135]
# Description
When I installed ZygiskNext, it won't work and it shown like it just installed, no error, nothing.

# Screenshot

![Screenshot_20240807-004615_Magisk](https://github.com/user-attachments/assets/ac8eda97-96fa-4349-a171-14e7ed684e97)
![Screenshot_20240807-004619_Magisk](https://github.com/user-attachments/assets/912df2c7-fc3c-4a5d-a229-02599bcff260)

# How to reproduce
- Install ZygiskNext on Binder64 devices and reboot
- Volia, it happened.

# Devices that I tested
Samsung Galaxy A6+ (a605g | a6plte)
OS : AncientOS v6.4
Magisk Varient : Default

**Comment by toonshouin** [comment]
... is there someone can help with this issue?

**Comment by 5ec1cff** [comment]
where is the log?

**Comment by toonshouin** [comment]
@5ec1cff  Sorry for the late reply, here.
https://gist.github.com/toonnongaeoy/efadfa78c23530673915faf82e66e4c6

**Comment by 5ec1cff** [comment]
Please provide boot log, magisk log is useless
