### ISSUE TITLE
please add support for Grephene OS Android14

### ISSUE THREAD

**Issue by sabamdarif** [Dr-TSNG/ZygiskOnKernelSU#140]
The official Magisk removed support for GrapheneOS Android 14, making it hard to use LSPosed on GrapheneOS, especially on VoltageOS (based to Graphene os). Currently, only [R6687BB53-kitsune](https://github.com/HuskyDG/magisk-files/releases/tag/1720171347) supports it. 
Please add this to your plans if possible.

**Comment by 5ec1cff** [comment]
Interesting.
