### ISSUE TITLE
License change violates GPL

### ISSUE THREAD

**Issue by mrmathematica** [Dr-TSNG/ZygiskOnKernelSU#141]
Facts: This project says "Zygisk Next, starting from version v4-0.9.2, is no longer under the GPL-3.0 License." Versinos before v4-0.9.2 is under GPL. v4-0.9.2 and later versions are developed on top of existing code base, instead of a complete rewrite.

Reasoning: GPL says any modifacation of GPLed software, if released, must also be released under GPL. One can't simply modify already GPLed sortware and turned it into Private, then release the binary only. That is exactly what GPL DOES NOT ALLOW.

**Comment by uqsme** [comment]
@mrmathematica https://www.gnu.org/licenses/gpl-faq.html#DeveloperViolate

**Comment by MiRinChan** [comment]
Do not forget LICENSE WONT LIMIT AUTHOR, even though code already licensed by GPL. Author always have ability to change license.

**Comment by vvb2060** [comment]
Please contact the copyright owner and ask him to sue the project for violating the open source license.

**Comment by androidacy-user** [comment]
> Facts: This project says "Zygisk Next, starting from version v4-0.9.2, is no longer under the GPL-3.0 License." Versinos before v4-0.9.2 is under GPL. v4-0.9.2 and later versions are developed on top of existing code base, instead of a complete rewrite.
> 
> Reasoning: GPL says any modifacation of GPLed software, if released, must also be released under GPL. One can't simply modify already GPLed sortware and turned it into Private, then release the binary only. That is exactly what GPL DOES NOT ALLOW.

You cannot relicense **other's** works but you can relicense your own. So, if someone's copyright was violated by close sourcing their contributions, theoretically _they_ could sue, but the author has the full rights to relicense their work at will by law.

**Comment by Dr-TSNG** [comment]
> other's works

ALL works made from LSPosed team. I beg you have a single glance at the contributor list.

**Comment by leohearts** [comment]
> No Claim to Succession: Any fork of the software that was created before the license change may not claim to be an official or unofficial successor to the project. This includes but is not limited to using the project's name, branding, or reputation to imply a connection to the original project.

Note that this won't make any sense because forks before this license change only has the old license applied. This won't affect forks to the original branch even after today either, because the old branch (or some specific commit ) is still GPL and being distributed.
So if anyone want to make your own fork and continue this project, just ignore this stuff.

**Comment by Dr-TSNG** [comment]
Fuck you

**Comment by Dr-TSNG** [comment]
> > No Claim to Succession: Any fork of the software that was created before the license change may not claim to be an official or unofficial successor to the project. This includes but is not limited to using the project's name, branding, or reputation to imply a connection to the original project.
> 
> Note that this won't make any sense because forks before this license change only has the old license applied. This won't affect forks to the original branch even after today either, because the old branch (or some specific commit ) is still GPL and being distributed. So if anyone want to make your own fork and continue this project, just ignore this stuff.

Fuck you

**Comment by leohearts** [comment]
> > > No Claim to Succession: Any fork of the software that was created before the license change may not claim to be an official or unofficial successor to the project. This includes but is not limited to using the project's name, branding, or reputation to imply a connection to the original project.
> > 
> > 
> > Note that this won't make any sense because forks before this license change only has the old license applied. This won't affect forks to the original branch even after today either, because the old branch (or some specific commit ) is still GPL and being distributed. So if anyone want to make your own fork and continue this project, just ignore this stuff.
> 
> Fuck you

Just don't make it GPL if you don't want to. You can change the license but it won't revoke the license for historical code.
To clarify, I didn't start the issue and it is pretty good to attack on somebody on GitHub, right ?

**Comment by Dr-TSNG** [comment]
> > > > No Claim to Succession: Any fork of the software that was created before the license change may not claim to be an official or unofficial successor to the project. This includes but is not limited to using the project's name, branding, or reputation to imply a connection to the original project.
> > > 
> > > 
> > > Note that this won't make any sense because forks before this license change only has the old license applied. This won't affect forks to the original branch even after today either, because the old branch (or some specific commit ) is still GPL and being distributed. So if anyone want to make your own fork and continue this project, just ignore this stuff.
> > 
> > 
> > Fuck you
> 
> Just don't make it GPL if you don't want to. You can change the license but it won't revoke the license for historical code. To clarify, I didn't start the issue and it is pretty good to attack on somebody on GitHub, right ?

操你妈，傻逼玩意给你脸了，分不清商标和代码的低能玩意，以为自己是个超级懂哥？你想fork旧代码没人管你，但别鸡巴不改名字嗯蹭。topjohnwu也要求fork不准用magisk这个名字，你是不是也要给他写个小作文啊？
