### ISSUE TITLE
Unable to boot into system after installing using KernelSU

### ISSUE THREAD

**Issue by BlueGradientHorizon** [Dr-TSNG/ZygiskOnKernelSU#142]
### **Tested on:**
- **Device**: POCO F5 (`marble`, `marble_global`, `23049PCD8G`)
- **OS**: stock HyperOS 1.0.6.0.UMRMIXM (A14, `UKQ1.230804.001`)
- **Kernel**: stock `5.10.198-android12-9-00085-g226a9632f13d-ab11136126`
- **KSU mode**: LKM
- **KSU version**: 11928 (both kernel and manager)
- **Previously installed modules**: `Adreno Gpu Driver` by LH (assume it works fine and doesn't cause any interference)
- **ZygiskNext version**: `1.1.0 (330-a1b0e69-release)`

### **Description:**
After I install this module in KSU manager app and reboot, the phone will stuck at first boot screen with POCO logo instead of playing HyperOS boot animation as if it was correct boot process. Then I need to do a force reboot by holding power button for 10s (the phone will reboot itself anyway in ~1-2 minutes). After force rebooting, system boots up correctly. In KSU manager the toggle switch of Zygisk Next module is staying activated, but message about successfull injection in module description is absent. The directory `/data/adb/modules/zygisksu` only contains `module.prop` file. 

### **Logs**
[Zip achive with logs from `/data/adb/ksu/log`](https://github.com/user-attachments/files/16946813/log.zip)
`dmesg.old.log` and `logcat.old.log` are from unsuccessfull boot (stuck at POCO logo).
`dmesg.log` and `logcat.log` are from successfull boot after force rebooting.

If you need some other logs if any, please provide information on how to get them.

**Comment by JasonKhew96** [comment]
`logcat.old.log`
![image](https://github.com/user-attachments/assets/b64b9f5a-7c96-4e65-8207-87f1247a607e)

**Comment by BlueGradientHorizon** [comment]
Hmm, I was reading logs for 10 mins and didn't noticed that. I'm sorry. Will retest it without adreno module ASAP.
