### ISSUE TITLE
Can't open LSP or ZN since enforcing DenyList

### ISSUE THREAD

**Issue by bphd** [Dr-TSNG/ZygiskOnKernelSU#147]
I guess some applications needs OverLayFS mounted on them, and enforcing don't mount anymore on them so I can't open, but I'm stuck if I don't guess which

**Comment by Astoritin** [comment]
There is no solutions if you insisting of enabling enforcing Denylist. Zygisk Next is not a module assisting hiding root at all either.

**Comment by bphd** [comment]
It's not about hiding root, I just want to be able to open ZN now

**Comment by bphd** [comment]
Okay so the app auto-softlock itself and nothing will be done about it

As long as open issue number reduces, better KPI ig

**Comment by aviraxp** [comment]
What does open ZN mean?

**Comment by bphd** [comment]
The GUI
