### ISSUE TITLE
Telegram apps are not working

### ISSUE THREAD

**Issue by CanerKaraca23** [Dr-TSNG/ZygiskOnKernelSU#151]
Telegram apps (wallet, blum etc.) are not working when i upgrade to 1.2.0 (including all preview versions)

I have latest official stable Telegram.

1.1.0 works fine, i downgraded.

I think something wrong with Android System WebView.

**Comment by 5ec1cff** [comment]
invalid

**Comment by CanerKaraca23** [comment]
> invalid

 What should I do so that it is not invalid?
