### ISSUE TITLE
Module Deactivating & Showing No Info

### ISSUE THREAD

**Issue by ThePieMonster** [Dr-TSNG/ZygiskOnKernelSU#153]
See the attached screenshot.

Magisk 27005

Pixel 6 Pro 
Android 13 

https://i.postimg.cc/MG9WXftv/Screenshot-20241016-093220.png

**Comment by 5ec1cff** [comment]
please provide boot log  ( https://t.me/hwrtools/12 )

**Comment by ThePieMonster** [comment]
The issue seems to be adding the [Pixelify	v3.0 by kingsman44](https://github.com/Kingsman44/Pixelify) on Magisk 27000 / 27005 / 27008 which causes a boot loop.

I need to fastboot my boot image and then get into safe mode and then just restart the device normally to get back into it. 



Not sure how I can get a log dump for you in this case. 

If I disable ZygiskNext and enable built in Zygisk in Magisk then I can run any version of Pixelify just fine.

**Comment by ThePieMonster** [comment]
@5ec1cff are there any logs we can view to see what the issue is? Why is your module not playing nice with Pixelify?

**Comment by aviraxp** [comment]
Why are you ignoring the method 5ec1cff provided to catch logs?

**Comment by 5ec1cff** [comment]
> please provide boot log ( https://t.me/hwrtools/12 )

**Comment by ThePieMonster** [comment]
> Why are you ignoring the method 5ec1cff provided to catch logs?

Why are you ignoring the post I made above yours that shows I am not able too.

The log catcher returns nothing. Its not able to capture any logs. I tried running it many times at different intervals during the boot process (before, during, and after). The log folder is empty. Yes I did make sure that root was granted to shell before I started any of this. 

Is there some other method for capturing the log files during boot?

**Comment by 5ec1cff** [comment]
try https://t.me/hwrtools/10

**Comment by ThePieMonster** [comment]
The below setup keeps the device running (you can see the image below). 

After adding the following module and the rebooting the device the device boots to recovery/fastboot screen. https://github.com/Kingsman44/Pixelify

You can not get the device to boot again. Any ideas? There are no log files that gets placed in the downloads folders after the Pixelify module is added since the device will no longer boot. 

I need a way to capture the boot process as the device is booting from the PC somehow. @5ec1cff 

![Screenshot_20241019-231315](https://github.com/user-attachments/assets/676cc67e-3747-4042-a50a-37fb01d21c5f)

**Comment by 5ec1cff** [comment]
> There are no log files that gets placed in the **downloads folders** after the Pixelify module is added ...

![image](https://github.com/user-attachments/assets/4f29c8b7-13da-4d83-88b2-0b85b232ae4a)

**Comment by ThePieMonster** [comment]
I do not have a cahce folder and the /data/local folder has a "access denied" error. @5ec1cff

**Comment by 5ec1cff** [comment]
Please use a root file explorer

**Comment by ThePieMonster** [comment]
This is the local folder. Nothing of use is in here however. @5ec1cff 

[local.zip](https://github.com/user-attachments/files/17448967/local.zip)

**Comment by 5ec1cff** [comment]
what about /cache ?

**Comment by ThePieMonster** [comment]
So I just briefly looked at the bootlogs. And you will notice that the first (10-19) is showing Magisk 27007 which is the boot before adding the in the Pixelify module. 

The second bootlog file (10-20) shows Magisk 27000. This is because after the Pixelify module is installed and the device keeps boot looping to recovery, I can not flashboot magisk_patched-27007 as that does not solve the issue. But what does get me back into the device is if I flash magisk_patched-27000. When I get into the device after the fastboot flash, all the Magisk modules are disabled. So that's probably why there is no other "helpful" boot log.

Let me know if you want me to try anything else. @5ec1cff 

[cache.zip](https://github.com/user-attachments/files/17450723/cache.zip)

**Comment by ThePieMonster** [comment]
Hello @5ec1cff 

I tried the new module version (see screenshot) however I am still having the same issue. 

The dump does't seem to have anything after hour mark ~23:30. Device was rebooted around ~23:45 which is 5 minutes after the Pixelify module was added.

[dump.zip](https://github.com/user-attachments/files/17454787/dump.zip)

<details>
  <summary>Screenshot</summary>
     <img src=https://github.com/user-attachments/assets/a76e6925-9f5e-426d-bff4-20f6e2ce9e7f></img>

</details>

I used the following for the [Pixelify](https://github.com/Kingsman44/Pixelify) setup
/sdcard/Pixelify/config.prop - [config.prop.txt](https://github.com/user-attachments/files/17454714/config.prop.txt)

**Comment by 5ec1cff** [comment]
Please provide /data/tombstones and /data/system/dropbox

**Comment by ThePieMonster** [comment]
> Please provide /data/tombstones and /data/system/dropbox

https://drive.google.com/drive/folders/1RDppBaTG42OYRsrgcQbrePccSPmlRf9i?usp=sharing

**Comment by 5ec1cff** [comment]
[Zygisk-Next-1.2.1.1-434-3d817b6-release.zip](https://github.com/user-attachments/files/17464126/Zygisk-Next-1.2.1.1-434-3d817b6-release.zip)

try this

**Comment by ThePieMonster** [comment]
@5ec1cff  Same issue. Crashing 1 to 2 seconds after the "Google" logo appears. Does not make it to the spinning part of the logo. 

Needed to flash back to 27000 and then after the Google logo appears hold down power and volume down to force safe boot and then normal reboot back into the device. All Magisk modules are disabled at that point. 

[Debug Files](https://drive.google.com/drive/folders/1RDppBaTG42OYRsrgcQbrePccSPmlRf9i?usp=sharing)

<details>
  <summary>Modules That I Enabled At The Time Of Crash</summary>
     <img src=https://github.com/user-attachments/assets/4f28c474-0ce3-4233-a8a2-1ab2f9883efd></img>
</details>

**Comment by 5ec1cff** [comment]
[mylogcat.zip](https://github.com/user-attachments/files/17470920/mylogcat.zip)
Install this module, reproduce the issue and send /cache

**Comment by ThePieMonster** [comment]
> [mylogcat.zip](https://github.com/user-attachments/files/17470920/mylogcat.zip) Install this module, reproduce the issue and send /cache

I am getting a installation failed error on log line 3 in Magisk.

**Comment by 5ec1cff** [comment]
?

**Comment by ThePieMonster** [comment]
<details>
  <summary>Error</summary>
     <img src=https://github.com/user-attachments/assets/051df8a5-e3ad-46a5-b89f-85b19a7dbc09></img>
</details>

**Comment by 5ec1cff** [comment]
extract service,sh and module.prop to /data/adb/modules/mylogcat

**Comment by 5ec1cff** [comment]
[mylogcat.zip](https://github.com/user-attachments/files/17484150/mylogcat.zip)

**Comment by ThePieMonster** [comment]
I am testing out Magisk 27005 this time instead of 27007/27008 also.

In this instance, the device rebooted a few times and then booted up. Did not boot to fastboot mode. (This is just how 27005 seems to be). So when the device turned on I looked at Magisk and all the modules were disabled so I booted into fastboot (since the device lost its root) and flashed 27005. Then booted the device and copied the cache folder.

<details>
  <summary>To reproduce the issue all I do here is enable the two Pixelify modules</summary>
     <img src=https://github.com/user-attachments/assets/fe0ebc0c-9663-4416-afb6-eb36e823e415></img>
</details>

[cache.zip](https://github.com/user-attachments/files/17484326/cache.zip)

**Comment by 5ec1cff** [comment]
please also enable hwr_logcat

**Comment by ThePieMonster** [comment]
[cache.zip](https://github.com/user-attachments/files/17484657/cache.zip)

<details>
  <summary>To reproduce the issue all I do here is enable the two Pixelify modules</summary>
     <img src=https://github.com/user-attachments/assets/314448a8-a014-4d50-ac03-d3127995d7a4></img>
</details>

**Comment by 5ec1cff** [comment]
These log files are corrupted. Please clear /cache dir, install the latest ZN (1.2.2) and retry

**Comment by 5ec1cff** [comment]
Please also provide /sys/fs/pstore/* when you send logs

**Comment by ThePieMonster** [comment]
Installed 1.2.2.
[cache.zip](https://github.com/user-attachments/files/17485161/cache.zip)
[pstore.zip](https://github.com/user-attachments/files/17485160/pstore.zip)

**Comment by aviraxp** [comment]
@ThePieMonster Can you access adb during device boot and capture logs?

**Comment by ThePieMonster** [comment]
I ran the following: `adb logcat`

Logcat stops recording after the first crash. The device reboots about 3 times before it boots up with no root and all modules disabled. @5ec1cff  @aviraxp 

[logcat-before.txt](https://github.com/user-attachments/files/17499398/logcat-before.txt)
[logcat-after.txt](https://github.com/user-attachments/files/17499399/logcat-after.txt)

**Comment by 5ec1cff** [comment]
[Zygisk-Next-1.2.2-437-3a6aabe-release.zip](https://github.com/user-attachments/files/17503212/Zygisk-Next-1.2.2-437-3a6aabe-release.zip)
try this

**Comment by ThePieMonster** [comment]
Hey, that one looks like it did the trick! Everything seems to be working as intended. 
What ended up being the fix? @5ec1cff 
[logcat.txt](https://github.com/user-attachments/files/17514645/logcat.txt)

**Comment by aviraxp** [comment]
Great! This will be fixed in ZygiskNext 1.2.3.

**Comment by ThePieMonster** [comment]
Was this needed because of how the Pixelify module is setup? Just wondering if any other module that used the same setup as Pixelfiy would have also caused the same issue. (I do not know of any modules that are setup in a manor such however). @5ec1cff  @aviraxp 

`This is a temporary module generated by ZN, which is used to complete tasks such as mounting files included in the zygisk module, loading system.prop, and mounting znctl. This module will not copy files to occupy actual storage space, and will be removed when ZN is disabled/uninstalled. Please feel free to use it.`

**Comment by 5ec1cff** [comment]
？
