### ISSUE TITLE
Failed to Inject Init (v1.2)

### ISSUE THREAD

**Issue by TheJoyOfDeath** [Dr-TSNG/ZygiskOnKernelSU#154]
[boot-2024-10-17-10-55-41.log](https://github.com/user-attachments/files/17410134/boot-2024-10-17-10-55-41.log)
Phone model is actually SM-N986B

I've just tried the new version and received the "Failed to inject init" error in modules. 
In the CP version shows as "failed to get version"

**Comment by aviraxp** [comment]
[Zygisk-Next-1.2.0-417-3c9d65e-release.zip](https://github.com/user-attachments/files/17411407/Zygisk-Next-1.2.0-417-3c9d65e-release.zip)
try this

**Comment by TheJoyOfDeath** [comment]
Awesome, thanks! That fixed the issue. 

Unfortunately I might have an overheating/drain issue that affected me on 1.1 and now has kicked in with 1.2 as well. But I'll post another report for that. Just making sure it's definitely an issue before posting.
