### ISSUE TITLE
ZygiskNext not working properly after disabling the built-in zygisk in magisk (Samsung Galaxy J400M)

### ISSUE THREAD

**Issue by devruntime** [Dr-TSNG/ZygiskOnKernelSU#158]
### Steps to reproduce/复现步骤

1- Enable zygisk built-in magisk and reboot
2- Disable zygisk built-in magisk and reboot
3- Install zygisknext module and reboot

### Expected behaviour/预期行为

I need zygisknext to work properly after disabling zygisk built-in in magisk
![Screenshot_2](https://github.com/user-attachments/assets/9a41b005-ab26-4157-8d85-dba875621cc3)

### Actual behaviour / 实际行为

When I disable zygisk built-in by magisk, some modules do not work showing the following message: "module suspended because zygisk is disabled", as if they do not detect zygisk next, they only work if I enable zygisk built-in magisk
![Screenshot_20241025-120333](https://github.com/user-attachments/assets/b4bba739-f24e-459e-93d0-7f10f6f2594f)
![Screenshot_20241025-120339](https://github.com/user-attachments/assets/80d95c3d-c8c9-4417-9f2b-3ae2c3ead850)

### Module List / 模块列表

```Shell
Play Integrity Fix v17.9
Tricky Store V1.2.0-RC2
Universal GMS Doze v1.9.1
Zygisk LSPosed v1.9.2
Zygisk Assistant v2.1.3
Zygisk Next 1.2.2
```

### Zygisk Next version / Zygisk Next 版本

ZygiskNext 1.2.2

### Android version / Android 版本

Android 10

### Magisk/KernelSU/APatch version / Magisk/KernelSU/APatch 版本

Magisk Canary 28001

### Version requirement / 版本要求

- [X] I am using latest version of Zygisk Next/我正在使用最新版本 Zygisk Next

### Logs/日志

[Uploading boot_log.txt…]()

**Comment by 5ec1cff** [comment]
u didn't even upload the logs correctly

**Comment by devruntime** [comment]
I'm sorry
[boot_log.txt](https://github.com/user-attachments/files/17525146/boot_log.txt)

**Comment by 5ec1cff** [comment]
Is your ROM 32bit only?

**Comment by devruntime** [comment]
Yes, only works on 64 bit rooms?

**Comment by 5ec1cff** [comment]
Sure.

**Comment by devruntime** [comment]
Thanks, i'll I will perform tests and try again
