### ISSUE TITLE
[Bug] Magisk 27008 Causing Crash

### ISSUE THREAD

**Issue by ThePieMonster** [Dr-TSNG/ZygiskOnKernelSU#159]
### Steps to reproduce/复现步骤

Crash seems to happen to quick for logcat this time. 

Reference issue below. 
https://github.com/Dr-TSNG/ZygiskNext/issues/153

### Expected behaviour/预期行为

N/A

### Actual behaviour / 实际行为

N/A

### Module List / 模块列表

```Shell
N/A
```

### Zygisk Next version / Zygisk Next 版本

1.2.3

### Android version / Android 版本

13

### Magisk/KernelSU/APatch version / Magisk/KernelSU/APatch 版本

27008

### Version requirement / 版本要求

- [X] I am using latest version of Zygisk Next/我正在使用最新版本 Zygisk Next

### Logs/日志

https://drive.google.com/drive/folders/1qL4gJyfgniQHbnxIMLj5NpoNIxMqt1rZ?usp=sharing

**Comment by 5ec1cff** [comment]
invalid report

**Comment by ThePieMonster** [comment]
@5ec1cff 
We just fixed the 27005 issue in the thread I linked.

**Comment by ThePieMonster** [comment]
@5ec1cff What do you need?

**Comment by 5ec1cff** [comment]
So why did u post it again?

**Comment by ThePieMonster** [comment]
@5ec1cff this report is for 27008. Which crashes at a different point in the boot process.

**Comment by 5ec1cff** [comment]
I didn't see any crashes, and u didn't tell me

**Comment by ThePieMonster** [comment]
ADB Logcat doesn't seem to be gathering any logs after the device turns back ON.  @5ec1cff 
-after was collected during shutdown. 
-after2 was collected on startup.

[logcat-after.txt](https://github.com/user-attachments/files/17673267/logcat-after.txt)
[logcat-after2.txt](https://github.com/user-attachments/files/17673268/logcat-after2.txt)

**Comment by 5ec1cff** [comment]
I can't download your logcat-after2.txt

**Comment by ThePieMonster** [comment]
> I can't download your logcat-after2.txt

@5ec1cff Its actually just a empty file. I was showing that I can't get any logs. I need some other method to get logs.

**Comment by 5ec1cff** [comment]
You can try disabling modules one by one to find out what causes the crash

**Comment by ThePieMonster** [comment]
@5ec1cff Same module as listed here: https://github.com/Dr-TSNG/ZygiskNext/issues/153

**Comment by 5ec1cff** [comment]
You need to do it yourself

**Comment by ThePieMonster** [comment]
@5ec1cff Do what myself? I already know whats causing the issue. Your module is conflicting with Pixelify as shown in the previous post.

**Comment by 5ec1cff** [comment]
But you can't provide any logs

**Comment by ThePieMonster** [comment]
@5ec1cff What logs do you want?

**Comment by 5ec1cff** [comment]
Boot logs when you installed the two modules

**Comment by ThePieMonster** [comment]
@5ec1cff Yes, but what method of log collection do you want besides `abd logcat` which I already provided. logcat doesn't collect on the crash since it happens to early in the boot process.

**Comment by 5ec1cff** [comment]
Provide /sys/fs/pstore/* or /proc/last_kmsg

**Comment by ThePieMonster** [comment]
@5ec1cff 

`/sys/fs/pstore/`
Empty Folder

`/proc/last_kmsg`
Does Not Exist

<br/><br/>

Will the `Log Catcher v22.5` or `My Log Catcher v1` provide any logs?

This file (`bootlog-yyyy-mm-dd-hh-mm-ss.tar`) won't be possible to get as the device does not boot however.

**Comment by ThePieMonster** [comment]
This bootlog came from `/cache/bootlog`. However, I believe this file was created after I re-flashed Magisk 27005. 

Magisk 28001 crashes the device and sends it to fastboot mode. So I then need to flash 27005 to get the device working again. The below file may not be useful as it lists the Magisk version at 27005. 

[boot-2024-11-09-19-42-12.log](https://github.com/user-attachments/files/17689802/boot-2024-11-09-19-42-12.log)

**Comment by ThePieMonster** [comment]
Video that shows the device crash. 
https://vimeo.com/1028060694

**Comment by 5ec1cff** [comment]
Which ROM are you using? Doesn't it support pstore ?

**Comment by ThePieMonster** [comment]
> Which ROM are you using? Doesn't it support pstore ?

@5ec1cff  I am not using a ROM. Just the standard OS that comes with the Pixel 6 Pro _Android 13_.

**Comment by ThePieMonster** [comment]
@5ec1cff I Tried the 1.2.4 module. Still crashing but seems like its in a slightly different spot after the Google logo appears. 

When I try to capture logs with `adb logcat` i get the following:
<img width="439" alt="image" src="https://github.com/user-attachments/assets/5735a0aa-0dbd-42c9-a477-d125801f2361">

**Comment by ThePieMonster** [comment]
I found this in the pstore folder. I added a `.txt` extension to it so I could upload. @5ec1cff 
[console-ramoops-0.txt](https://github.com/user-attachments/files/17742574/console-ramoops-0.txt)

**Comment by 5ec1cff** [comment]
Unless you provide valid logs, the problem cannot be solved. I suggest you continue to use Magisk 27005

**Comment by ThePieMonster** [comment]
@5ec1cff 

Does the PStore log I provided above not help at all? 

Would using a emulator instead of a physical device be easier to capture logs perhaps?

**Comment by 5ec1cff** [comment]
The pstore you provided does not contain any ZN logs, not even magisk's

**Comment by ThePieMonster** [comment]
There isn't anything I can control over that.
