### ISSUE TITLE
Latest build causes boot loop 

### ISSUE THREAD

**Issue by Fighteros** [Dr-TSNG/ZygiskOnKernelSU#163]
### Steps to reproduce/复现步骤

I'm on apatch latest stable just install latest update and my device got stuck on boot logo 

device poco x3 pro vayu
rom : miui 13 a13 elite lite rom

### Expected behaviour/预期行为

To just work fine

### Actual behaviour / 实际行为

System break

### Module List / 模块列表

```Shell
play intgrity fix
```

### Zygisk Next version / Zygisk Next 版本

1.2.4

### Android version / Android 版本

12

### Magisk/KernelSU/APatch version / Magisk/KernelSU/APatch 版本

Apatch 10763

### Version requirement / 版本要求

- [X] I am using latest version of Zygisk Next/我正在使用最新版本 Zygisk Next

### Logs/日志

Not fixed

**Comment by 5ec1cff** [comment]
no log no fix
