### ISSUE TITLE
KernelSU itself error

### ISSUE THREAD

**Issue by Sadyantssr** [Dr-TSNG/ZygiskOnKernelSU#164]
### Steps to reproduce/复现步骤

Tried installing latest zip file

### Expected behaviour/预期行为

Installation successfully 

### Actual behaviour / 实际行为

Error - Function not implemented (os error 38)
Exit code - 1

### Module List / 模块列表

```Shell
No gravity kernel helper module
```

### Zygisk Next version / Zygisk Next 版本

1.2.4

### Android version / Android 版本

14

### Magisk/KernelSU/APatch version / Magisk/KernelSU/APatch 版本

11184

### Version requirement / 版本要求

- [x] I am using latest version of Zygisk Next/我正在使用最新版本 Zygisk Next

### Logs/日志

[KernelSU_install_log_2024-11-17-22-00-08.log](https://github.com/user-attachments/files/17791443/KernelSU_install_log_2024-11-17-22-00-08.log)

**Comment by SteveZMTstudios** [comment]
@Sadyantssr using LKM kernelsu?

**Comment by Sadyantssr** [comment]
> @Sadyantssr using LKM kernelsu?
Don't know what that means, but i flashed ngk kernel then installed kernel su apk.

**Comment by 5ec1cff** [comment]
ask ksu plz
