### ISSUE TITLE
Some root detecting apps not working on latest versions 

### ISSUE THREAD

**Issue by elswerky** [Dr-TSNG/ZygiskOnKernelSU#166]
### Steps to reproduce/复现步骤

Hello
I sent you before that since you upgraded v 1.1 
I have issue in some root detecting apps like an app called ana Vodafone 

This app was working well with v 1.1 with a magisk kiysune and  and enforce denylist

Now if I upgraded to an newer version above 1.1 , like say latest 1.2.4 I get crash in this app
It only works with v 1.1 as told before 
Don't know why
Sent you before and you said nothing wrong from your side but I can tell you and you can test it only works with v 1.1 

https://play.google.com/store/apps/details?id=com.emeint.android.myservices

### Expected behaviour/预期行为

Expected app not to crash or detect root 

### Actual behaviour / 实际行为

Crash with any version above 1.1 

### Module List / 模块列表

```Shell
Just automatic brick rescue 
Zugisk next 
Lspsoed 1.93
```

### Zygisk Next version / Zygisk Next 版本

1.2.4 or 1.2 

### Android version / Android 版本

14 

### Magisk/KernelSU/APatch version / Magisk/KernelSU/APatch 版本

Kiysune latest 27001

### Version requirement / 版本要求

- [X] I am using latest version of Zygisk Next/我正在使用最新版本 Zygisk Next

### Logs/日志

From where to get logs but I send all link from play store since I don't know how to get logs

**Comment by elswerky** [comment]
Ok ,you closed it anyway 
Gonna test rezygisk
Thank you

**Comment by armv7a** [comment]
> Ok ,you closed it anyway Gonna test rezygisk Thank you

Zygisk Next is not for hiding
