### ISSUE TITLE
[Bug] Failed to spawn: process not found

### ISSUE THREAD

**Issue by Cold-Stars** [Dr-TSNG/ZygiskOnKernelSU#167]
### Steps to reproduce/复现步骤

1.使用magisk自带的zygisk没有这个问题
2.使用zygisknext会出现frida无法使用spawn模式

### Expected behaviour/预期行为

frida -U -f xxx -l .\test.js
成功

### Actual behaviour / 实际行为

frida -U -f xxx -l .\test.js

Failed to spawn: process not found

### Module List / 模块列表

```Shell
zygisk-jshook
zygisk-lsposed
爱玩机工具箱
```

### Zygisk Next version / Zygisk Next 版本

1.2.4

### Android version / Android 版本

安卓13

### Magisk/KernelSU/APatch version / Magisk/KernelSU/APatch 版本

Kitsune Mask 26.4-kitsune-2

### Version requirement / 版本要求

- [X] I am using latest version of Zygisk Next/我正在使用最新版本 Zygisk Next

### Logs/日志

[boot-2024-11-24-10-23-11.zip](https://github.com/user-attachments/files/17891504/boot-2024-11-24-10-23-11.zip)

**Comment by 5ec1cff** [comment]
关闭 magisk hide
