### ISSUE TITLE
模块未正常工作

### ISSUE THREAD

**Issue by Endlesssword** [Dr-TSNG/ZygiskOnKernelSU#18]
模块启用但是没有[zygisk is loaded]提示，lsposed显示未安装，系统是https://github.com/ponces/treble_build_pe
[KernelSU_bugreport_2023-04-13_11_29.tar.gz](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11234280/KernelSU_bugreport_2023-04-13_11_29.tar.gz)
![Screenshot_20230414-230204_KernelSU](https://user-images.githubusercontent.com/54000774/232083764-8c218473-aa10-4b6c-86a7-3e541f38493f.png)
![Screenshot_20230414-231307_KernelSU](https://user-images.githubusercontent.com/54000774/232084132-da4c7f44-1344-44f9-82fa-74c14e53a72a.png)

**Comment by tiann** [comment]
这个版本是否正常？https://github.com/tiann/KernelSU/releases/tag/v0.5.2

**Comment by 5ec1cff** [comment]
从 mounts 看 KernelSU 模块没挂载

**Comment by 5ec1cff** [comment]
那用 `adb wait-for-device logcat -b all > logs.txt`

**Comment by Endlesssword** [comment]
用adb版本的得到了这些 
[kmsg_2023-04-14_23-34-49.log](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11234554/kmsg_2023-04-14_23-34-49.log)
[all_2023-04-14_23-34-49.log](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11234538/all_2023-04-14_23-34-49.log)

**Comment by Endlesssword** [comment]
也不行，从0.5.1-release，然后在tg群的ci频道里从0.5.1-17（好像是）开始几乎每个版本都尝试了，都不加载，所以觉得很奇怪
[all_2023-04-14_23-43-45.log](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11234617/all_2023-04-14_23-43-45.log)

**Comment by Endlesssword** [comment]
安装了终端，但是不知道怎么用，直接su 然后复制命令他只会回复removing leading '/' from member names

**Comment by 5ec1cff** [comment]
> 安装了终端，但是不知道怎么用，直接su 然后复制命令他只会回复removing leading '/' from member names

这个先不用发了，看看上面的消息

**Comment by Endlesssword** [comment]
[Uploading KernelSU_bugreport_2023-04-15_01_21.tar.gz…]()
[all_2023-04-15_ 1-20-47.log](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11235480/all_2023-04-15_.1-20-47.log)
[kmsg_2023-04-15_ 1-20-48.log](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11235489/kmsg_2023-04-15_.1-20-48.log)

**Comment by 5ec1cff** [comment]
> 注意：
> 
> 1. 更换 manager 测试的情况下，安装后需要至少打开一次 manager 再重启
> 2. 你的开机日志不全，可以尝试在开发者选项中把日志缓冲区大小调到最大


你的 ksud post-fs-data 看起来正常启动了(从内核日志可以看出)，但是缺少它的 log ，看起来 post-fs-data 前的日志丢失了，可以尝试上面第二条，或者用https://github.com/tiann/KernelSU/actions/runs/4701804321 这个 CI 的内核(尝试启动 logd)

抓取日志后自行搜索有没有 /data/adb/ksud --post-fs-data 或者 ksud::cli command: PostFsData

**Comment by Endlesssword** [comment]
日志记录器缓冲区大小调到了8m，应该是最大了，然后内核也是刚出炉的10768，就是非常奇怪

**Comment by 5ec1cff** [comment]
你怎么抓的开机日志

**Comment by Endlesssword** [comment]
用的tg群里发的tools频道的log-catcher-adb-v5，按照底下说明操作的

**Comment by 5ec1cff** [comment]
init 也不出日志，正常来说应该有这种：

```
init    : starting service 'exec 13 (/data/adb/ksud post-fs-data)'
```

我的建议是换个系统

**Comment by 1001ace1001** [comment]
有相同的问题，不但是lsposed不加载，而且是所有zygisk模块失效~
[log.zip](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11238218/log.zip)

**Comment by 5ec1cff** [comment]
用这个 CI 的 manager 再抓看看：

https://github.com/tiann/KernelSU/actions/runs/4707163974

**Comment by Endlesssword** [comment]
[all_2023-04-16_13-27-08.log](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11241299/all_2023-04-16_13-27-08.log)
[kmsg_2023-04-16_13-27-08.log](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11241301/kmsg_2023-04-16_13-27-08.log)
[KernelSU_bugreport_2023-04-16_13_27.tar.gz](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11241302/KernelSU_bugreport_2023-04-16_13_27.tar.gz)

**Comment by 5ec1cff** [comment]
> [all_2023-04-16_13-27-08.log](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11241299/all_2023-04-16_13-27-08.log) [kmsg_2023-04-16_13-27-08.log](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11241301/kmsg_2023-04-16_13-27-08.log) [KernelSU_bugreport_2023-04-16_13_27.tar.gz](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11241302/KernelSU_bugreport_2023-04-16_13_27.tar.gz)

在任意 root shell 执行，发结果：

```
touch /mnt/a
mount --bind /system/etc/permissions/android.hardware.bluetooth.xml /mnt/a
```

**Comment by Endlesssword** [comment]
![Screenshot_20230416-151745_KernelSU](https://user-images.githubusercontent.com/54000774/232279997-655df3ca-9e10-4866-bf53-f72041d376eb.png)
[KernelSU_bugreport_2023-04-16_15_17.tar.gz](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11241489/KernelSU_bugreport_2023-04-16_15_17.tar.gz)
[all_2023-04-16_15-16-18.log](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11241490/all_2023-04-16_15-16-18.log)
只剩lsposed显示未安装了
