### ISSUE TITLE
红米k70pro从安卓14升级至安卓15之后模块版本1.0.4失效，模块升级1.2.4后卡在redmi开机界面

### ISSUE THREAD

**Issue by weeiq** [Dr-TSNG/ZygiskOnKernelSU#186]
### Steps to reproduce/复现步骤

1. 设备：k70pro，已解锁bl
2. 系统版本号：1.0.20.0.UNMCNXM
3. root平台：apatch（版本：0.10.7
4. 安装模块：去广告，安装httpcanary，音量极速救砖，爱玩机工具箱（应用核心功能拓展），zygisk-lsposed，zygisk next
5. 由安卓14-1.0.20.0.UNMCNXM升级到安卓15-2.0.4.0后，1.0.4版本不生效，所以升级到最新版后刷入不开机，
**还请帮忙看下怎么解决，感谢**
![4E65AC1B-58E5-40FA-B829-AAE434EE0D87](https://github.com/user-attachments/assets/b76f89fe-4086-437a-ab96-8102828deff0)
![image](https://github.com/user-attachments/assets/d0c41999-5b2b-4ca8-bbc1-3012c63bbb67)
![image](https://github.com/user-attachments/assets/c1a3cb03-d41c-478c-abb1-f59112f248ff)
![image](https://github.com/user-attachments/assets/61780e07-29f6-47c5-878c-3168ea9f49a5)

### Expected behaviour/预期行为

正常情况下再刷入完成后应正常开机

### Actual behaviour / 实际行为

卡在redmi界面
![8D3B9272-5F34-4238-9DAD-B8DB6748EE9F](https://github.com/user-attachments/assets/576d1ac1-a257-465c-832a-995606ded507)

### Module List / 模块列表

```Shell
4. 安装模块：去广告，安装httpcanary，音量极速救砖，爱玩机工具箱（应用核心功能拓展），zygisk-lsposed，zygisk next
```

### Zygisk Next version / Zygisk Next 版本

1.0.4，1.2.4

### Android version / Android 版本

15

### Magisk/KernelSU/APatch version / Magisk/KernelSU/APatch 版本

apatch 0.10.7

### Version requirement / 版本要求

- [X] I am using latest version of Zygisk Next/我正在使用最新版本 Zygisk Next

### Logs/日志

文件过大，已上传到服务器
http://38.6.223.21:28282/down/Kyl0ttDm0fWh.gz

**Comment by weeiq** [comment]
重新将所有模块卸载后再重新安装，已解决

**Comment by xiewenyi6882-source** [comment]
怎么解的bl
