### ISSUE TITLE
[Bug] Bootloop with V1.2.5

### ISSUE THREAD

**Issue by Fede2782** [Dr-TSNG/ZygiskOnKernelSU#187]
### Steps to reproduce/复现步骤

Flash V1.2.5

### Expected behaviour/预期行为

It should boot normally

### Actual behaviour / 实际行为

Bootloop. Kernel SU does module rollback

### Module List / 模块列表

```Shell
Zygisk Next + LSPosed Zygisk
```

### Zygisk Next version / Zygisk Next 版本

v1.2.5

### Android version / Android 版本

14

### Magisk/KernelSU/APatch version / Magisk/KernelSU/APatch 版本

v1.0.2

### Version requirement / 版本要求

- [X] I am using latest version of Zygisk Next/我正在使用最新版本 Zygisk Next

### Logs/日志

[KernelSU_bugreport_2024-12-11_22_07.tar.gz](https://github.com/user-attachments/files/18102412/KernelSU_bugreport_2024-12-11_22_07.tar.gz)

**Comment by 5ec1cff** [comment]
Disable the module `Improved Framework for One UI 6.1 (A34 5G)`

**Comment by Fede2782** [comment]
> Disable the module `Improved Framework for One UI 6.1 (A34 5G)`

Nono I have already tried disabling it. No success. As I said I tried only LSPosed Zygisk + ZygiskNext without success. Moreover that module just sets a single property.

**Comment by Fede2782** [comment]
I did a factory reset and reinstalled all modules as before. It now works. I installed Zygisk v1.2.5 as the first module and immediately rebooted after its installation. I then installed other modules
