### ISSUE TITLE
[Bug] Restart repeatedly.

### ISSUE THREAD

**Issue by Lythrilla** [Dr-TSNG/ZygiskOnKernelSU#188]
### Steps to reproduce/复现步骤

My mobile phone keeps restarting infinitely after being updated to the latest version of Zygisk.

### Expected behaviour/预期行为

Boot up normally. 

### Actual behaviour / 实际行为

After I installed Zygisk-Next and was prompted to restart, the phone got stuck on the boot interface. It didn't show the system logo and kept restarting infinitely.

### Module List / 模块列表

```Shell
音量键急速救砖
爱玩机工具箱（应用核心功能扩展）
Zygisk-Next
```

### Zygisk Next version / Zygisk Next 版本

1.2.5

### Android version / Android 版本

13

### Magisk/KernelSU/APatch version / Magisk/KernelSU/APatch 版本

APatch 0.10.7（10763）

### Version requirement / 版本要求

- [X] I am using latest version of Zygisk Next/我正在使用最新版本 Zygisk Next

### Logs/日志

[APatch_bugreport_2024-12-25_15_06.tar(1).gz](https://github.com/user-attachments/files/18244095/APatch_bugreport_2024-12-25_15_06.tar.1.gz)

**Comment by Lythrilla** [comment]
OnePlus Ace 2

**Comment by 5ec1cff** [comment]
升级你的 ap

**Comment by Lythrilla** [comment]
> 升级你的 ap

没用

**Comment by 5ec1cff** [comment]
有用
