### ISSUE TITLE
[Bug] ZYGISK NEXT CRASHES GOOGLE PLAY MARKET (com.android.vending)

### ISSUE THREAD

**Issue by Lobanokivan11** [Dr-TSNG/ZygiskOnKernelSU#189]
### Steps to reproduce/复现步骤

1. Flash Zygisk Next.
2. Restart a device.
3. Google play crashes instantly or if it's opened can't install any of app, download not working

### Expected behaviour/预期行为

google play need to opening and starting to install app

### Actual behaviour / 实际行为

Google play crashes instantly or if it's opened can't install any of app, download not working

### Module List / 模块列表

```Shell
Zygisk - Lsposed
```

### Zygisk Next version / Zygisk Next 版本

1.2.5

### Android version / Android 版本

15

### Magisk/KernelSU/APatch version / Magisk/KernelSU/APatch 版本

Magisk

### Version requirement / 版本要求

- [X] I am using latest version of Zygisk Next/我正在使用最新版本 Zygisk Next

### Logs/日志

[vending.txt](https://github.com/user-attachments/files/18253265/vending.txt)

**Comment by 5ec1cff** [comment]
I can't see anything useful in the logs.

**Comment by Lobanokivan11** [comment]
I am serious google play crashes while zygisk next works!!!

https://github.com/user-attachments/assets/c2bc418e-d393-4ca3-9ac2-e9a6d10fb55c
