### ISSUE TITLE
[Bug] Zygisk Next cause "Module suspended" visual effect

### ISSUE THREAD

**Issue by BadIDMan** [Dr-TSNG/ZygiskOnKernelSU#190]
### Steps to reproduce/复现步骤

Install Zygisk Next in Magisk-Kitsune fork downloaded from https://github.com/1q23lyc45/KitsuneMagisk/releases/tag/v27.2-kitsune-3.
Result:
![obraz](https://github.com/user-attachments/assets/f86d674f-c69c-4882-80f1-9849c74b6a92)

### Expected behaviour/预期行为

Another Zygisk fork like NeoZygisk correctly shows status in Magisk-Kitsune fork:
![obraz](https://github.com/user-attachments/assets/66967bdf-9ffe-4d20-89ce-cdc2a2f7916f)

Another Zygisk fork like ReZygisk correctly shows status in Magisk-Kitsune fork:
![obraz](https://github.com/user-attachments/assets/50b1e551-4314-4bec-8bee-0fec32dcc9d2)

### Actual behaviour / 实际行为

See in Steps to reproduce

### Module List / 模块列表

```Shell
Zygisk Next and few other
```

### Zygisk Next version / Zygisk Next 版本

1.2.5

### Android version / Android 版本

14

### Magisk/KernelSU/APatch version / Magisk/KernelSU/APatch 版本

Magisk v27.2-kitsune-3

### Version requirement / 版本要求

- [X] I am using latest version of Zygisk Next/我正在使用最新版本 Zygisk Next

### Logs/日志

No logs are needed. Bug is about visual presentation.

**Comment by 5ec1cff** [comment]
No support for kitsune

**Comment by 1q23lyc45** [comment]
https://www.gnu.org/proprietary/proprietary.html
