### ISSUE TITLE
[Bug] 模块未能正常工作

### ISSUE THREAD

**Issue by Womsxd** [Dr-TSNG/ZygiskOnKernelSU#22]
### Steps to reproduce/复现步骤

1. magisk/kernelSU刷入模块
2. 重启手机
3. zygisk加载失败

### Expected behaviour/预期行为

zygisk正常加载

### Actual behaviour/实际行为

模块加载失败

### KernelSU Module List/KernelSU 模块列表

```Shell
ColoOS13 X AOSP安装器 13.0.8
LogCatcher v22.5
Shamiko v0.7.1(166)
ShaerNearby Oneplus CN 1.0.2
Zygisk-Sui v13.0.1
Zygisk on KernelSU v4-0.6.5（78）
```

### Zygisk on KernelSU version/Zygisk on KernelSU 版本

https://github.com/Dr-TSNG/ZygiskOnKernelSU/actions/runs/4762932124

### Android version/Android 版本

13

### KernelSU version/KernelSU 版本

KernelSU:v0.5.5 &Magisk:26100

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk on KernelSU and enable verbose log/我正在使用最新 CI 调试版本 Zygisk on KernelSU 且启用详细日志

### Logs/日志
[bootlog-2023-05-13-09-15-20.tar.gz](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11468589/bootlog-2023-05-13-09-15-20.tar.gz)

[magisk_log_2023-05-13T09.19.07.log](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11468591/magisk_log_2023-05-13T09.19.07.log)

![Screenshot_2023-05-13-09-18-08-12](https://github.com/Dr-TSNG/ZygiskOnKernelSU/assets/45663319/39762a47-9214-4eba-96c5-bf7583e0a4b7)

**Comment by Womsxd** [comment]
kernelSU环境下的日志
[KernelSU_bugreport_2023-05-13_09_42.tar.gz](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11468614/KernelSU_bugreport_2023-05-13_09_42.tar.gz)
[bootlog.tar.gz](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11468616/bootlog.tar.gz)

**Comment by 5ec1cff** [comment]
```
01-28 02:19:13.635   933   933 W KernelSU: ksud::event: mount system failed: mount overlayfs for root failed: mount overlayfs on /system options lowerdir=/data/adb/modules/zygisksu/system:/data/adb/modules/AOSPInstaller/system:/system failed: Operation not permitted (os error 1)
```

**Comment by suh2j** [comment]
你怎么在magisk里装这模块？magisk自带zygisk啊

**Comment by Womsxd** [comment]
> 你怎么在magisk里装这模块？magisk自带zygisk啊

测试用，kernelsu里面没法使用就丢magisk里面试试看
