### ISSUE TITLE
安装模块提示kernelsu版本过旧

### ISSUE THREAD

**Issue by bags432** [Dr-TSNG/ZygiskOnKernelSU#23]
### Steps to reproduce/复现步骤

拉取kerensu最新源码编译Image
刷入boot.img
安装Zygisk-on-KernelSU-v4-0.6.5-78-release

### Expected behaviour/预期行为

安装成功

### Actual behaviour/实际行为

安装失败，提示版本过旧

### KernelSU Module List/KernelSU 模块列表

```Shell
没安装其他模块
```

### Zygisk on KernelSU version/Zygisk on KernelSU 版本

Zygisk-on-KernelSU-v4-0.6.5-78-release

### Android version/Android 版本

13

### KernelSU version/KernelSU 版本

16(kernel)+10866(ksud)

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk on KernelSU and enable verbose log/我正在使用最新 CI 调试版本 Zygisk on KernelSU 且启用详细日志

### Logs/日志

_ __       
/\ /\___ _ __ _ __   ___| / _\/\ /\ 
/ //_/ _ \ '__| '_ \ / _ \ \ \/ / \ \
/ __ \  __/ |  | | | |  __/ |\ \ \_/ /
\/  \/\___|_|  |_| |_|\___|_\__/\___/

- Preparing image
- Module size: 3.76 MB
- Estimated minimum size of the filesystem: 4415
- Target image size: 75.39 MB
resize2fs 1.46.2 (28-Feb-2021)
- Mounting image
- Current boot slot: _a
- Device is system-as-root
*********************
 Zygisk on KernelSU 
 by Nullptr, 5ec1cff 
*********************
*********************
 Powered by KernelSU 
*********************
- Installing from KernelSU app
- KernelSU version: 16 (kernel) + 10866 (ksud)
*********************************************************
! KernelSU version is too old!
! Please update KernelSU to latest version
*********************************************************
- Error: Failed to install module script
Error: Failed to install module script

**Comment by Dr-TSNG** [comment]
顾名思义
