### ISSUE TITLE
[Bug] Short description/简单描述

### ISSUE THREAD

**Issue by Kronodile** [Dr-TSNG/ZygiskOnKernelSU#25]
### Steps to reproduce/复现步骤

1. Update to kernel su 16

### Expected behaviour/预期行为

Zygisk on kernelsu should work as normal 

### Actual behaviour/实际行为

Zygisk in kernelsu manager says "X Root implementation version too old] Run Zygisk on KernelSU."

### KernelSU Module List/KernelSU 模块列表

```Shell
Zygisk, Zygisk lsposed, zygisk storage isolation, YouTube rvx, aosp mkds
```

### Zygisk on KernelSU version/Zygisk on KernelSU 版本

 v4-0.6.5 (78)

### Android version/Android 版本

13

### KernelSU version/KernelSU 版本

16

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk on KernelSU and enable verbose log/我正在使用最新 CI 调试版本 Zygisk on KernelSU 且启用详细日志

### Logs/日志

Is logzip really required, because problem is simple from what I understand. Kernelsu changed its version number from 10xxxx something to just 16 and zygisk module thinks this is a lower kernelsu version hence not supported. Bumping up the minimum version flag in module should fix everything

**Comment by cracky5322** [comment]
@Kronodile This is a problem with your Ksu kernel, not a module

**Comment by Kronodile** [comment]
> @Kronodile This is a problem with your Ksu kernel, not a module

How is this a ksu kernel problem? The version checking flag on zygisk module has to be updated

**Comment by Dr-TSNG** [comment]
Joking. The latest ksu version is 10904.
