### ISSUE TITLE
一加 ace2刷入成功，但是lsposed和别的zygisk相关模块都没生效

### ISSUE THREAD

**Issue by 2046553272** [Dr-TSNG/ZygiskOnKernelSU#27]
### Steps to reproduce/复现步骤

刷入0.7.0(85-release)就有，0.6.*一切正常

### Expected behaviour/预期行为

模块正常运行

### Actual behaviour/实际行为

0.7.0(85)刷入后关于zygisk模块都没有生效直接闪退，kernelsu的设置里面关了默认卸载模块后重启后也是一样的结果，
![Screenshot_2023-06-09-14-47-02-99_084ab3bc34f7aa7ccff83653f52abafc](https://github.com/Dr-TSNG/ZygiskOnKernelSU/assets/70498814/3d404119-0e4b-423e-b7e0-2d97ff875d6d)

### KernelSU Module List/KernelSU 模块列表

```Shell
Zygisk on KernelSU
Zygisk lsposed
Zygisk sui
Zygisk - Enhanced mode for Storage Isolation
```

### Zygisk on KernelSU version/Zygisk on KernelSU 版本

v4-0.7.0 (85-release)

### Android version/Android 版本

android13

### KernelSU version/KernelSU 版本

0.6.0(10981)

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk on KernelSU and enable verbose log/我正在使用最新 CI 调试版本 Zygisk on KernelSU 且启用详细日志

### Logs/日志

[KernelSU_bugreport_2023-06-09_15_51.tar.gz](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11703750/KernelSU_bugreport_2023-06-09_15_51.tar.gz)

**Comment by 5ec1cff** [comment]
用 debug
https://github.com/Dr-TSNG/ZygiskOnKernelSU/actions/runs/5166988579

**Comment by 2046553272** [comment]
> 用 debug https://github.com/Dr-TSNG/ZygiskOnKernelSU/actions/runs/5166988579

问题就是用debug就正常了
[KernelSU_bugreport_2023-06-09_16_11.tar.gz](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11703930/KernelSU_bugreport_2023-06-09_16_11.tar.gz)
