### ISSUE TITLE
[Bug] Zygisk not working properly, that's why shamiko also not working 

### ISSUE THREAD

**Issue by guruji-byte** [Dr-TSNG/ZygiskOnKernelSU#28]
### Steps to reproduce/复现步骤

kernelSU V 0.6.0-10
Zygisk debug v85
Shamiko 0.7.3

### Expected behaviour/预期行为

Actually Shamiko not working because zygisk KSU not working properly just showing that " zygisk loaded on zygote"
I don't know the actually what's missing 

### Actual behaviour/实际行为

![Screenshot_20230610-192524](https://github.com/Dr-TSNG/ZygiskOnKernelSU/assets/132416069/bead229c-139c-40c9-aa8d-e4b136e9130f)
![Screenshot_20230608-133244](https://github.com/Dr-TSNG/ZygiskOnKernelSU/assets/132416069/a267a179-9d97-456a-b914-e2c20759c68e)

### KernelSU Module List/KernelSU 模块列表

```Shell
Shamiko 0.7.3
Zygisk KSU debug v85
```

### Zygisk on KernelSU version/Zygisk on KernelSU 版本

Zygisk KSU debug v85

### Android version/Android 版本

12

### KernelSU version/KernelSU 版本

0.6.0

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk on KernelSU and enable verbose log/我正在使用最新 CI 调试版本 Zygisk on KernelSU 且启用详细日志

### Logs/日志

[KernelSU_bugreport_2023-06-10_19_27.tar.gz](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11712574/KernelSU_bugreport_2023-06-10_19_27.tar.gz)

**Comment by Dr-TSNG** [comment]
Useless log, everything has been covered. Install lsposed and send its logs.

**Comment by guruji-byte** [comment]
Okay

**Comment by guruji-byte** [comment]
After flashing lsposed and zygisk sui module my problem solved.
Thank you very much sir.
My favourite man on this earth

**Comment by guruji-byte** [comment]
[KernelSU_bugreport_2023-06-10_20_26.tar.gz](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11712697/KernelSU_bugreport_2023-06-10_20_26.tar.gz)

**Comment by guruji-byte** [comment]
This log after flashing lsposed
Now shamiko working but lsposed not working

**Comment by Dr-TSNG** [comment]
I said send **lsposed log**, instread of ksu's. Zip /data/adb/lspd/log.

**Comment by guruji-byte** [comment]
[log.zip](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11712713/log.zip)

**Comment by guruji-byte** [comment]
Shamiko working after flashing lspd module, its not working if I uninstalled lspd, I don't know it's a bug or not sir

**Comment by Dr-TSNG** [comment]
The log shows lsposed is working

**Comment by guruji-byte** [comment]
But if I uninstalled lsposed then shamiko not works

**Comment by Dr-TSNG** [comment]
Install log catcher module and use it to catch logs. (with shamiko only)
https://t.me/hwrtools/10

**Comment by guruji-byte** [comment]
Installed 
![Screenshot_20230610-205900](https://github.com/Dr-TSNG/ZygiskOnKernelSU/assets/132416069/24ecc667-ccf1-428d-9fae-76c0e635e280)

**Comment by Dr-TSNG** [comment]
So send ur log

**Comment by guruji-byte** [comment]
[hwr_logcat.zip](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11712744/hwr_logcat.zip)

**Comment by guruji-byte** [comment]
![Screenshot_20230610-210725](https://github.com/Dr-TSNG/ZygiskOnKernelSU/assets/132416069/4a042c39-a99a-4e7c-b1e0-03823a326d8b)
What about this

**Comment by guruji-byte** [comment]
Still showing lspd
![Uploading Screenshot_20230610-210918.png…]()

**Comment by guruji-byte** [comment]
![Screenshot_20230610-210918](https://github.com/Dr-TSNG/ZygiskOnKernelSU/assets/132416069/34436207-8b09-4cbb-9143-a0f4ec9e7957)

**Comment by Dr-TSNG** [comment]
What the fuck are you sending

**Comment by guruji-byte** [comment]
[boot-2023-06-10-21-03-15.log](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11712763/boot-2023-06-10-21-03-15.log)

**Comment by guruji-byte** [comment]
There are another zip file containing old boot log in same folder. Also need that?

**Comment by guruji-byte** [comment]
> What the fuck are you sending

[boot-2023-06-10-21-03-15.log](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11712785/boot-2023-06-10-21-03-15.log)
