### ISSUE TITLE
Shamiko not working 

### ISSUE THREAD

**Issue by guruji-byte** [Dr-TSNG/ZygiskOnKernelSU#29]
### Steps to reproduce/复现步骤

kernelSU 0.6.0-10
Shamiko 0.7.3
Log Catcher 

### Expected behaviour/预期行为

Shamiko should be working fine with Zygisk KSU

### Actual behaviour/实际行为

Shamiko not working without lsposed 

### KernelSU Module List/KernelSU 模块列表

```Shell
Log Catcher
Shamiko 0.7.3
```

### Zygisk on KernelSU version/Zygisk on KernelSU 版本

Zygisk KSU debug v85

### Android version/Android 版本

12

### KernelSU version/KernelSU 版本

0.6.0

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk on KernelSU and enable verbose log/我正在使用最新 CI 调试版本 Zygisk on KernelSU 且启用详细日志

### Logs/日志

[boot-2023-06-10-21-03-15.log](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11712804/boot-2023-06-10-21-03-15.log)
[oldlogbak.tar.gz](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11712805/oldlogbak.tar.gz)
There are both logs old and new (after flashing log Catcher)
And sorry for last time

**Comment by Howard20181** [comment]
@guruji-byte Why you don't install zygisk on KernelSU?

**Comment by guruji-byte** [comment]
Check recent bug
