### ISSUE TITLE
Samsung S22 Plus Can't install ZygiskOnKernelSU 

### ISSUE THREAD

**Issue by jetecho** [Dr-TSNG/ZygiskOnKernelSU#3]
When I install ZygiskOnKernelSU  at Samsung S22 Plus it failed and tell me 
"! Your Kernel may not support SElinux patch fully"
![image](https://user-images.githubusercontent.com/69247016/217753234-3deb0b84-c680-469f-bcca-b6ef09bd7e19.png)

**Comment by Dr-TSNG** [comment]
Update your ksu manager or it's just literally not supported.
