### ISSUE TITLE
Lsposed not working 

### ISSUE THREAD

**Issue by guruji-byte** [Dr-TSNG/ZygiskOnKernelSU#30]
### Steps to reproduce/复现步骤

KernelSU Version 10981 
ZygiskSU V85
Lsposed 6904

### Expected behaviour/预期行为

Lsposed should be working fine 

### Actual behaviour/实际行为

At first reboot after installing ZygiskSU, Lsposed, and Shamiko everything works well but after second reboot lsposed breaks only Shamiko works and if I uninstall lsposed Shamiko also breaks I tried both Debug and normal version same problem with both of them

### KernelSU Module List/KernelSU 模块列表

```Shell
ZygiskSU V85
Lsposed V6904
Shamiko v174
Zygisk sui v13.0.1
```

### Zygisk on KernelSU version/Zygisk on KernelSU 版本

V85

### Android version/Android 版本

13

### KernelSU version/KernelSU 版本

10981

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk on KernelSU and enable verbose log/我正在使用最新 CI 调试版本 Zygisk on KernelSU 且启用详细日志

### Logs/日志

![Screenshot_20230611-163257](https://github.com/Dr-TSNG/ZygiskOnKernelSU/assets/132416069/767b0b58-471e-4aba-88e6-b4997281006a)
![Screenshot_20230611-163310](https://github.com/Dr-TSNG/ZygiskOnKernelSU/assets/132416069/461151b8-7ecd-40ec-800e-b0d6e4448d12)
![Screenshot_20230611-163318](https://github.com/Dr-TSNG/ZygiskOnKernelSU/assets/132416069/22d73ea9-d0fa-44fd-b541-556adf3bac5f)
[log.zip](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11714436/log.zip)

**Comment by guruji-byte** [comment]
I can also send log of debug

**Comment by Dr-TSNG** [comment]
> I am using latest debug CI version of Zygisk on KernelSU and enable verbose log

不认识字的话我建议你重新去上小学再来说话
