### ISSUE TITLE
[Bug] Zygisk on KernelSU Triggers LIAPP Root Detection

### ISSUE THREAD

**Issue by RecursiveRegistrations** [Dr-TSNG/ZygiskOnKernelSU#37]
### Steps to reproduce/复现步骤

1. Install [Blind](https://play.google.com/store/apps/details?id=com.teamblind.blind) on a phone rooted with KernelSU.
2. Attempt to use Blind. It will work properly.
3. Force stop Blind, clear data, and clear cache.
4. Make sure that "Unmount modules by default" is enabled in the KernelSU manager.
5. Install Zygisk on KernelSU and reboot.
6. Attempt to use Blind. The LIAPP root detection error will appear even though Blind should not be able to see Zygisk.

### Expected behaviour/预期行为

Blind should be able to function even with Zygisk enabled.

### Actual behaviour/实际行为

Blind throws the LIAPP root detection error.

### KernelSU Module List/KernelSU 模块列表

```Shell
1. Blobmoji version 15.1 Beta, Release 1
2. Busybox for Android NDK version 1.34.1
3. Pixel 4 2 Button Navigation
4. Universal SafetyNet Fix version v2.4.0-MOD_1.3 (Displax)
5. App Systemizer version 17.3.1
6. LSPosed version 1.8.6
7. Shamiko version 0.7.3
8. Enhanced Mode for Storage Isolation version 28.1.0
9. Zygisk on KernelSU
```

### Zygisk on KernelSU version/Zygisk on KernelSU 版本

Zygisk-on-KernelSU-v4-0.7.1-91-ceaa2d4-debug

### Android version/Android 版本

13

### KernelSU version/KernelSU 版本

Manager Version v0.6.1 | Kernel 5.10.177-android13-4

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk on KernelSU and enable verbose log/我正在使用最新 CI 调试版本 Zygisk on KernelSU 且启用详细日志

### Logs/日志

[bugreport-raven-TQ3A.230605.010-2023-07-07-00-20-31.zip](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/11974501/bugreport-raven-TQ3A.230605.010-2023-07-07-00-20-31.zip)

**Comment by russel5** [comment]
Im do not have this issue with app
Installed zygisk, enabled "unmount modules"
Blind works without any problem

**Comment by RecursiveRegistrations** [comment]
@russel5 Could you tell me what other modules you have installed?

**Comment by RecursiveRegistrations** [comment]
@Dr-TSNG Were you able to reproduce this?

**Comment by russel5** [comment]
Samsung s22 ultra sm-s908e
13 android
Zygisk on kernelsu latest
Lsposed latesl
Knoxpatch enhanced latest
Universal safetynet fix mod by displax latest

**Comment by RecursiveRegistrations** [comment]
@russel5 Thanks! Are you using the global unmount or the app-specific one? Neither one works for me. :(

**Comment by RecursiveRegistrations** [comment]
@Dr-TSNG I asked the KernelSU team [here](https://github.com/tiann/KernelSU/issues/727) about this issue and they tell me that the problem originates with this module. Could you please tell me what the reason was for closing this?
