### ISSUE TITLE
[Question] A game which detects zygisk

### ISSUE THREAD

**Issue by ToucH9000** [Dr-TSNG/ZygiskOnKernelSU#38]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Is 8 ball pool working after enabling zygisk in KernelSU?

### Describe the solution you'd like/描述你想要的解决方案

I want to play 8 ball pool after enabling zygisk.

**Comment by Zulfi121** [comment]
Same happened here too, after enable zygisk in ksu 8 ball pool crashes.
