### ISSUE TITLE
[Bug] Short description/简单描述

### ISSUE THREAD

**Issue by nehonpa** [Dr-TSNG/ZygiskOnKernelSU#39]
### Steps to reproduce/复现步骤

大佬抱歉，请允许我在这里反馈一个关于shamiko模块中的白名单模式的问题，经过我多次的测试，发现开启了白名单模式的shamiko会导致我magisk中的Move Certificates移动用户证书到系统证书的这个模块失效。
可能是因为白名单模式的全局屏蔽root导致的Move Certificates没有权限移动证书，所以想请大佬尝试修复这个问题可以吗？没有添加到系统证书导致我无法使用查尔斯或是其他抓包工具顺利抓取https的请求。

### Expected behaviour/预期行为

经过测试，把shamiko关闭后重启，Move Certificates模块就能正常工作了。

### Actual behaviour/实际行为

开启了白名单模式的shamiko会导致我magisk中的Move Certificates移动用户证书到系统证书的这个模块失效。

### KernelSU Module List/KernelSU 模块列表

```Shell
我只有安装LSP框架与Move Certificates模块，以及shamiko模块
下方日志中以上传了我使用的所有模块及版本。KernelSU我没有使用，那个版本号是随便填的
```

### Zygisk on KernelSU version/Zygisk on KernelSU 版本

26.1

### Android version/Android 版本

Android 10

### KernelSU version/KernelSU 版本

0.0.0

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk on KernelSU and enable verbose log/我正在使用最新 CI 调试版本 Zygisk on KernelSU 且启用详细日志

### Logs/日志

[movecert-1.9-4.zip](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/12091040/movecert-1.9-4.zip)
[Shamiko-v0.7.3-174-release.zip](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/12091041/Shamiko-v0.7.3-174-release.zip)
[LSPosed-v1.8.6-6712-zygisk-release.zip](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/12091043/LSPosed-v1.8.6-6712-zygisk-release.zip)

**Comment by 5ec1cff** [comment]
请不要在这里反馈非 zksu 的问题

冷知识：系统证书不一定要用模块，你可以单独给 app 进程挂载证书（同时，Shamiko 仍然是生效的）

**Comment by Dr-TSNG** [comment]
我觉得不要在 issue 里问跟项目完全不相关的问题是一个基本常识呢，你不会以为你能得到答复吧
