### ISSUE TITLE
[Feature Request] 取消kernelSU的zygisk和system分区的挂载读写的冲突

### ISSUE THREAD

**Issue by WYF-2013** [Dr-TSNG/ZygiskOnKernelSU#40]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

kernelSU的zygisk会占用system的分区，使得本来能读写system分区变得无法挂载。
当然无论是只使用magisk的zygisk还是只关闭kernelSU的zygisk（使用纯净的root权限）都不会对system分区的读写造成影响。
我的系统版本是安卓13，红米k60pro，内核版本5.15.104，kernelSU版本v0.6.2（11089），zygiskONmagisk版本v4-0.7.1-89-release。

### Describe the solution you'd like/描述你想要的解决方案

我请求能取消kernelSU的zygisk和system分区的挂载读写的冲突，或者给出开关。

### Additional context/其他信息

system分区为ext4已解锁，在kernelSU不安装zygisk环境下成功读写，在magisk开启zygisk模式下成功读写。

**Comment by Dr-TSNG** [comment]
差不多得了
