### ISSUE TITLE
[Bug] Zygiskd crashing with 2 modules

### ISSUE THREAD

**Issue by Damima3369** [Dr-TSNG/ZygiskOnKernelSU#43]
### Steps to reproduce/复现步骤

1. Install ZygiskOnKSU latest 
2. Install Lsposed latest
3. Reboot and check that Zygisk & Lsposed works properly
4. Install Basic Call Recorder latest
5. Reboot
6. Zygiskd crashed and Lsposed not working, congratulations 

SPOILER: BCR + Zygisk works properly and Zygisk+LSPosed works properly, Zygisk crashing only when BCR + Lsposed installed

### Expected behaviour/预期行为

Zygiskd not crashing, Lsposed works

### Actual behaviour/实际行为

In KSU "Zygiskd has crashed", Lsposed not working 

### KernelSU Module List/KernelSU 模块列表

```Shell
BCR v1.46
unOfficial_iOS16 1.3 beta
Zygisk - LSPosed v1.8.6(6712)
Zygisk on KernelSU v4.0.7.1 (89 release)
Rosemary font
My bootanimation changer
```

### Zygisk on KernelSU version/Zygisk on KernelSU 版本

v4.0.7.1 (89 release)

### Android version/Android 版本

13

### KernelSU version/KernelSU 版本

11101 kernel, 11184 manager 

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk on KernelSU and enable verbose log/我正在使用最新 CI 调试版本 Zygisk on KernelSU 且启用详细日志

### Logs/日志

[KernelSU_bugreport_2023-08-12_09_11.tar.gz](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/12326766/KernelSU_bugreport_2023-08-12_09_11.tar.gz)

**Comment by Dr-TSNG** [comment]
*I am using latest debug CI version of Zygisk on KernelSU and enable verbose log*

**Comment by Damima3369** [comment]
> _I am using latest debug CI version of Zygisk on KernelSU and enable verbose log_

Oh, I'm sorry, idk, I think it is not debug, I downloaded it from releases, and idk where is verbose log, I didn't read where I ticked

**Comment by Damima3369** [comment]
Solution found! Idk why, but Zygisk not working with any moduleS, it can work with only one, if Shamiko is not installed. Idk, I've installed Shamiko for test 5 minutes ago, and all works, now installed 2-3 modules that using Zygisk, zygiskd is not crashing
