### ISSUE TITLE
[Bug] 编译rust部分报错

### ISSUE THREAD

**Issue by liumengdeqq** [Dr-TSNG/ZygiskOnKernelSU#46]
### Steps to reproduce/复现步骤

 1../gradlew task module:zipDebug

### Expected behaviour/预期行为

编译产生zip

### Actual behaviour/实际行为

> Task :zygiskd:cargoBuildArm FAILED
    Updating git repository `https://github.com/Kernel-SU/binder_rs`
error: no matching package named `binder` found
location searched: https://github.com/Kernel-SU/binder_rs
required by package `zygiskd v1.0.0 (/Users/xxx/zygisk_module/ZygiskOnKernelSU/zygiskd)`

FAILURE: Build failed with an exception.

### KernelSU Module List/KernelSU 模块列表

```Shell
xx
```

### Zygisk on KernelSU version/Zygisk on KernelSU 版本

master

### Android version/Android 版本

android 10

### KernelSU version/KernelSU 版本

v0.6.6

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk on KernelSU and enable verbose log/我正在使用最新 CI 调试版本 Zygisk on KernelSU 且启用详细日志

### Logs/日志

> Task :zygiskd:cargoBuildArm FAILED
    Updating git repository `https://github.com/Kernel-SU/binder_rs`
error: no matching package named `binder` found
location searched: https://github.com/Kernel-SU/binder_rs
required by package `zygiskd v1.0.0 (/Users/xxx/zygisk_module/ZygiskOnKernelSU/zygiskd)`

FAILURE: Build failed with an exception.

**Comment by Dr-TSNG** [comment]
Check ur proxy

**Comment by 5ec1cff** [comment]
上游模块改了名字
