### ISSUE TITLE
[Feature Request] Use native bridge to inject

### ISSUE THREAD

**Issue by BlackMesa123** [Dr-TSNG/ZygiskOnKernelSU#47]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Not an actual issue, but this would bring a better codebase (imho)

### Describe the solution you'd like/描述你想要的解决方案

Is there a chance this could be implemented in the project? https://github.com/topjohnwu/Magisk/pull/6659

**Comment by Howard20181** [comment]
This project has been using the native bridge since the beginning.
