### ISSUE TITLE
[Feature Request] Enable modules on Magisk when zygisk is disabled

### ISSUE THREAD

**Issue by yashikada** [Dr-TSNG/ZygiskOnKernelSU#48]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Yes

### Describe the solution you'd like/描述你想要的解决方案

I'd like enable modules on Magisk when zygisk is disabled and this module is installed and enabled

### Additional context/其他信息

Could you enable.discussion for your project please?

**Comment by Dr-TSNG** [comment]
I don't know what you mean, but zygisksu has always triggered `post-fs-data.sh` and `service.sh` for zygisk modules  manually because magisk will not do that when original zygisk is disabled.
