### ISSUE TITLE
Installing on BlissOS with permissive SELinux

### ISSUE THREAD

**Issue by hmtheboy154** [Dr-TSNG/ZygiskOnKernelSU#5]
Hi, I'm trying to install this on BlissOS, this is a custom build with Kernel 6.1.12

![Screenshot_20230219-190055_KernelSU](https://user-images.githubusercontent.com/39849246/220079073-84357890-4bda-4d21-8f43-73108d3cc292.png)

Here is my dmesg 
[dmesg.txt](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/10783366/dmesg.txt)

**Comment by Dr-TSNG** [comment]
check_sepolicy is provided by ksud, so report to KernelSU instead of here.
