### ISSUE TITLE
Unable to put system in R/W

### ISSUE THREAD

**Issue by bklynali** [Dr-TSNG/ZygiskOnKernelSU#54]
### Steps to reproduce/复现步骤

If I uninstall the module in kernelsu I can mount the system r/w, while the module is installed unable to put the system in r/w its only r/o

### Expected behaviour/预期行为

none

### Actual behaviour/实际行为

none

### KernelSU Module List/KernelSU 模块列表

```Shell
zygisk
```

### Zygisk on KernelSU version/Zygisk on KernelSU 版本

4-0.7.1-89

### Android version/Android 版本

13 and 14

### KernelSU version/KernelSU 版本

11274

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk on KernelSU and enable verbose log/我正在使用最新 CI 调试版本 Zygisk on KernelSU 且启用详细日志

### Logs/日志

n/a

**Comment by Dr-TSNG** [comment]
I feel very sorry that you are blind.
`Note: We will NEVER handle any issue related to root detection or writable system.`
