### ISSUE TITLE
Zygisk Being detected (Shamiko)

### ISSUE THREAD

**Issue by noobz-id** [Dr-TSNG/ZygiskOnKernelSU#57]
### Steps to reproduce/复现步骤

latest ZygiskOnKernelSU is being detected just by:

```
cat /proc/self/mounts | grep zygisk
```

i check with RootXplorer to see inside folder /dev and i see zygisk/ folder in here. 

but in previous version everything is work fine.

I Apologize if i report issue in here, i think just shamiko module bugs not support the new ZygiskOnKernelSU. but i can't commit the new issue in Shamiko Module repository.. 

my setup:
- KernelSU 11272 (manager 0.6.9) (latest)
- ZygiskOnKernelSU v4-0.8.0 (latest)
- Shamiko v0.7.4 (latest)

### Expected behaviour/预期行为

Shamiko Module fix maybe ?

### Actual behaviour/实际行为

Bugs on Shamiko Module ?

### KernelSU Module List/KernelSU 模块列表

```Shell
ZygiskOnKernelsu, Shamiko
```

### Zygisk on KernelSU version/Zygisk on KernelSU 版本

ZygiskOnKernelSU v4-0.8.0 (latest)

### Android version/Android 版本

13

### KernelSU version/KernelSU 版本

KernelSU 11272 (manager 0.6.9) (latest)

### Version requirement/版本要求

- [x] I am using latest debug CI version of Zygisk on KernelSU and enable verbose log/我正在使用最新 CI 调试版本 Zygisk on KernelSU 且启用详细日志

### Logs/日志

i no have logs, but i thing is clear :)

**Comment by Dr-TSNG** [comment]
1. /dev/zygisk will be replaced with /debug_ramfisk/zygisk when ksu switches overlayfs to magic mount
2. shamiko will trigger unmount if u configured correctly

**Comment by noobz-id** [comment]
The issue i wrote above is Look like this.


![Screenshot_2023-10-23-16-22-28-536_me weishu kernelsu](https://github.com/Dr-TSNG/ZygiskOnKernelSU/assets/30004380/b0fc43bf-0376-44c9-839e-9004972da277)
![Screenshot_2023-10-23-16-22-49-423_me weishu kernelsu](https://github.com/Dr-TSNG/ZygiskOnKernelSU/assets/30004380/f475fc11-e772-42e2-962b-281f4445b60f)
![Screenshot_2023-10-23-16-23-23-008_yarolegovich materialterminal](https://github.com/Dr-TSNG/ZygiskOnKernelSU/assets/30004380/4d6c2de0-5e91-42b2-bfc4-f9902ec5bf04)

**Comment by Dr-TSNG** [comment]
install debug version from actions and provide logs

**Comment by noobz-id** [comment]
Logs in kernelsu ?
[KernelSU_bugreport_2023-10-23_16_34.tar.gz](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/13068572/KernelSU_bugreport_2023-10-23_16_34.tar.gz)

**Comment by Dr-TSNG** [comment]
I have said install **DEBUG** version

**Comment by noobz-id** [comment]
Oh sorry my bad, i search the debug version but i didn't found ..

**Comment by Dr-TSNG** [comment]
https://github.com/Dr-TSNG/ZygiskOnKernelSU/actions/runs/6598759703

**Comment by noobz-id** [comment]
Oh ok, ... I install the ZygiskOnKernelSU-debug from your link above..

I send new logs from kernelsu right ?

[KernelSU_bugreport_2023-10-23_17_17.tar.gz](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/13068904/KernelSU_bugreport_2023-10-23_17_17.tar.gz)

**Comment by Dr-TSNG** [comment]
material terminal is 32 bit and zygisksu now only supports 64 bit processes

**Comment by noobz-id** [comment]
Just for more info...
If I downgrade the zygiskOnKSU (v4-0.7.1) the stable previous version ..

And try the test i do above. Zygisk is hidden perfectly.

![Screenshot_2023-10-23-17-33-20-703_me weishu kernelsu](https://github.com/Dr-TSNG/ZygiskOnKernelSU/assets/30004380/1d9171b9-2020-4fbe-9f71-93e9b15b6e5c)
![Screenshot_2023-10-23-17-33-33-508_me weishu kernelsu](https://github.com/Dr-TSNG/ZygiskOnKernelSU/assets/30004380/03f7b15f-84d0-4bca-8b29-4e002c486e22)
![Screenshot_2023-10-23-17-33-56-970_yarolegovich materialterminal](https://github.com/Dr-TSNG/ZygiskOnKernelSU/assets/30004380/5e2ccf01-a88d-4777-89fa-1020cf4c9390)

**Comment by Dr-TSNG** [comment]
Why don't you read the changelog? 32 bit support is dropped in 0.8.0

**Comment by 5kind** [comment]
> 1. /dev/zygisk will be replaced with /debug_ramdisk/zygisk when ksu switches overlayfs to magic mount
> 2. shamiko will trigger unmount if u configured correctly

About replace /dev/zygisk to /debug_randisk, is that a feature not updated in the latest release? I use zygisk next on magisk and still find /dev/zygisk.
