### ISSUE TITLE
[Bug]Zygisk-on-KernelSU-v4-0.8.0-106 

### ISSUE THREAD

**Issue by hxj827796034** [Dr-TSNG/ZygiskOnKernelSU#58]
### Steps to reproduce/复现步骤

Zygisk-on-KernelSU-v4-0.8.0-106 不兼容LSPosed 开机黑屏 电源重启开机 lsposed模块全部失效 有时候重启会自动卸载全部模块

### Expected behaviour/预期行为

开机黑屏 强制开机 安装模块没有效果 失效

### Actual behaviour/实际行为

开机黑屏 强制开机 安装模块没有效果 失效

### KernelSU Module List/KernelSU 模块列表

```Shell
Zygisk-on-KernelSU-v4-0.8.0-106 
shamiko  074
zygisk-lsposed
```

### Zygisk on KernelSU version/Zygisk on KernelSU 版本

Zygisk-on-KernelSU-v4-0.8.0-106 

### Android version/Android 版本

10

### KernelSU version/KernelSU 版本

11272

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk on KernelSU and enable verbose log/我正在使用最新 CI 调试版本 Zygisk on KernelSU 且启用详细日志

### Logs/日志

[KernelSU_bugreport_2023-10-23_17_25.tar.gz](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/13068476/KernelSU_bugreport_2023-10-23_17_25.tar.gz)

**Comment by Dr-TSNG** [comment]
去 actions 下 debug 版本安装再发一遍日志

**Comment by 5ec1cff** [comment]
你要重新安装 lsposed

**Comment by Dr-TSNG** [comment]
日志太晚了，打包一下 /data/adb/lspd/log 发过来

**Comment by hxj827796034** [comment]
[KernelSU_bugreport_2023-10-23_18_36.tar.gz](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/13069051/KernelSU_bugreport_2023-10-23_18_36.tar.gz)

**Comment by hxj827796034** [comment]
[log.zip](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/13069082/log.zip)

**Comment by Dr-TSNG** [comment]
上传的文件有问题，下载不了，麻烦重新上传一遍

**Comment by hxj827796034** [comment]
[KernelSU_bugreport_2023-10-23_18_36.tar.gz](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/13069444/KernelSU_bugreport_2023-10-23_18_36.tar.gz)

**Comment by hxj827796034** [comment]
[log.zip](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/13069455/log.zip)

**Comment by Dr-TSNG** [comment]
system_server 崩掉了，是新版本才出现的 bug 还是旧版本就存在？

**Comment by hxj827796034** [comment]
> system_server 崩掉了，是新版本才出现的 bug 还是旧版本就存在？

4.-0.8.0

**Comment by hxj827796034** [comment]
> system_server 崩掉了，是新版本才出现的 bug 还是旧版本就存在？

旧版本 不存在

**Comment by skvalex** [comment]
LSPosed/Shamiko don't work on Pixel 8 with [v4-0.8.0](https://github.com/Dr-TSNG/ZygiskOnKernelSU/releases/tag/v4-0.8.0), but downgrading to version [v4-0.7.1](https://github.com/Dr-TSNG/ZygiskOnKernelSU/releases/tag/v4-0.7.1) helps.

**Comment by Dr-TSNG** [comment]
https://github.com/Dr-TSNG/ZygiskOnKernelSU/actions/runs/6623678530

**Comment by Dr-TSNG** [comment]
#59

**Comment by skvalex** [comment]
Version 0.8.1 still doesn't work with Shamiko/LSPosed on Pixel 8, downgraded to 0.7.1

**Comment by Dr-TSNG** [comment]
> Version 0.8.1 still doesn't work with Shamiko/LSPosed on Pixel 8, downgraded to 0.7.1

Open a new issue and provide logs
