### ISSUE TITLE
v4-0.5.0 causes crash on Play Store

### ISSUE THREAD

**Issue by Geniucker** [Dr-TSNG/ZygiskOnKernelSU#7]
After updating to v4-0.5.0, My Play Store will crash after opening it for several seconds. And Chrome have similar problem. Maybe there's something wrong with webview?
Phone: OnePlus 10 Pro
KernelSu version: 10654
Kernel:  5.10.101-android12-9-g30979850fc20
Android: 13

**Comment by Dr-TSNG** [comment]
Already fixed, wait for next release.
