### ISSUE TITLE
Lsposed crash in v4-0.9.1.1

### ISSUE THREAD

**Issue by anuragpindoriya** [Dr-TSNG/ZygiskOnKernelSU#86]
### Steps to reproduce/复现步骤

1. In v4-0.8.1 lsposed working perfectly fine 
2.  After receiving update v4-0.9.0  first time here lsposed was staring to crashing. 
3. Then after i receiving update v4-0.9.1.1 but behavior of lsposed was same it's keep crashing 
4. To test my theory i downgrade zygisk next to v4-0.8.1 and see lsposed now start working 
5. Some changes in v4-0.9.1.1 and v4-0.9.0 are prevent  lsposed to working 

Note :- for v4-0.9.1.1 i update ksu manager and kernel both to v0.7.5

### Expected behaviour/预期行为

Lsposed working find 

### Actual behaviour/实际行为

Lsposed keep crashing and not working

### KernelSU Module List/KernelSU 模块列表

```Shell
1. Knoxpatch  enhancer
2. KernelSU unmount modules
3. Magical overlayfs
4. Google photos unlimited backup 
5. Play integrity fix 
6. Youtube revanced 
7. Zygisk lsposed
7. Shamiko
8. Zygisk detach
9. Zygisk keystore blocker 
10. Zygisk sui
11. Zygisk next
```

### Zygisk Next version/Zygisk Next 版本

Latest ( v4-0.9.1.1 )

### Android version/Android 版本

13

### KernelSU version/KernelSU 版本

V0.7.5

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk Next and enable verbose log/我正在使用最新 CI 调试版本 Zygisk Next 且启用详细日志

### Logs/日志

[KernelSU_bugreport_2024-01-08_09_29.tar.gz](https://github.com/Dr-TSNG/ZygiskNext/files/13856118/KernelSU_bugreport_2024-01-08_09_29.tar.gz)

**Comment by 5ec1cff** [comment]
uninstall `KernelSU unmount modules`

**Comment by Dr-TSNG** [comment]
Never install multiple "hide" modules. 1+1<1
