### ISSUE TITLE
[Bug] AdAway doesn't show any error, but isn't able to write to host with all ZygiskNext version between v4-0.9.0-178 and v4-0.9.1.1-189

### ISSUE THREAD

**Issue by DJLeleX** [Dr-TSNG/ZygiskOnKernelSU#87]
### Steps to reproduce/复现步骤

1. Install [AdAway](https://github.com/AdAway/AdAway/releases/tag/v6.1.1)
2. Grant SuperUser permission to AdAway in KernelSU Manager
3. Install ZygiskNext v4-0.9.0-178 (or newer). (To send the bugreport I installed v4-0.9.1.1-189 debug version)
4. Install [systemless host KernelSU module](https://github.com/symbuzzer/systemless-hosts-KernelSU-module/releases/tag/v1.1.2)
5. Reboot to apply changes

### Expected behaviour/预期行为

Adaway should write to host file and block ads in web pages.

### Actual behaviour/实际行为

Adaway doesn't show any error and it tells the host file is updated with latest source, but it isn't working as expected because ads are still shown in web pages.

With all ZygiskNext version between v4-0.8.1-126 and v4-0.8.1-177 it was working fine.

### KernelSU Module List/KernelSU 模块列表

```Shell
- Busybox for Android NDK v1.36.1
- a little module to change samsung emoji to ios emoji I wrote myself
- KnoxPatch Enhancer v0.4
- Play Integrity Fix v15.1
- systemless host KernelSU module v1.1.2
- Zygisk - LSPosed v1.9.2 (7058)
- Shamiko v1.0.1 (300)
- ZygiskNext v4-0.9.1.1 (189-debug)
```

### Zygisk Next version/Zygisk Next 版本

v4-0.9.1.1-189 debug (all version between v4-0.9.0-178 and v4-0.9.1.1-189 have issue)

### Android version/Android 版本

12 (OneUI 4.1)

### KernelSU version/KernelSU 版本

kernel and manager v0.7.5 (11434)

### Version requirement/版本要求

- [X] I am using latest debug CI version of Zygisk Next and enable verbose log/我正在使用最新 CI 调试版本 Zygisk Next 且启用详细日志

### Logs/日志

[KernelSU_bugreport_2024-01-08_09_39.tar.gz](https://github.com/Dr-TSNG/ZygiskNext/files/13857846/KernelSU_bugreport_2024-01-08_09_39.tar.gz)

If you need bugreport from android developer option, let me know so I can upload it.

**Comment by DJLeleX** [comment]
I will downgrade to ZygiskNext v4-0.8.1-177 (latest working fine) for the time being. Please let me know if I need to test anything or provide any other logs.

**Comment by 5ec1cff** [comment]
Please give feedback to AdAway

**Comment by DJLeleX** [comment]
> Please give feedback to AdAway

Thanks, I will do it.

**Comment by Webpage-gh** [comment]
Clearing AdAway's data may solve this problem. Remember to back up third-party Hosts sources before clearing AdAway data.

**Comment by DJLeleX** [comment]
> Clearing AdAway's data may solve this problem. Remember to back up third-party Hosts sources before clearing AdAway data.

It didn't solve the issue. Thanks anyway, I found a chromium-based browser with extension support for android as a workaround.
