### ISSUE TITLE
请问后续能否支持apatch

### ISSUE THREAD

**Issue by Caribeankelp** [Dr-TSNG/ZygiskOnKernelSU#89]
目前新出了一个apatch的内核root工具，但是该工具只能使用修改版本的zygisk next才能使用，但目前贵项目已经不开源了，所以后续修改版无法使用，烦请贵开发者后续版本能否对apatch进行支持，万分感谢

**Comment by CC0126** [comment]
同求此功能，小米非gki内核不开源，第三方内核电流高（调度有问题/部分子系统无法休眠），卡顿，间歇性死机，ksu又不出lkm，确实很难办

**Comment by Caribeankelp** [comment]
> 求这个功能，小米非gki开源不开源，第三方开源电流高（调度有问题/部分子系统无法休眠），卡顿，间歇性死机，ksu又不出lkm，确实很难办

ksu的通用内核，兼容性一般，我的指纹和定位都有点小问题

**Comment by Memory2314** [comment]
解决方法 不用apatch

**Comment by Caribeankelp** [comment]
> https://github.com/Dr-TSNG/ZygiskNext/tree/master
> 
> 不开源？您仔细看看

我知道不开源，所以向开发者反馈，烦请原生开发者适配一下，如果开源肯定有人适配

**Comment by yxsra** [comment]
> > https://github.com/Dr-TSNG/ZygiskNext/tree/master
> > 不开源？您仔细看看
> 
> 我知道不开源，所以向开发者反馈，烦请原生开发者适配一下，如果开源肯定有人适配

v4-0.9.1.1 之前的是开源的,哪里不开源了。

**Comment by Caribeankelp** [comment]
> > > https://github.com/Dr-TSNG/ZygiskNext/tree/master
> > > 不开源？您仔细看看
> > 
> > 
> > 我知道不开源，所以向开发者反馈，烦请原生开发者适配一下，如果开源肯定有人适配
> 
> v4-0.9.1.1 之前的是开源的,哪里不开源了。

我说的是后续，明白了吗？后续zygisk next的版本更新开发者都说了不会开源，所以后续需要原来的开发者适配

**Comment by ShionKanagawa** [comment]
> > https://github.com/Dr-TSNG/ZygiskNext/tree/master
> > 不开源？您仔细看看
> 
> 我知道不开源，所以向开发者反馈，烦请原生开发者适配一下，如果开源肯定有人适配

眼睛和脑子一定缺少一个：https://github.com/Dr-TSNG/ZygiskNext/pull/88，而且这个 PR 的作者甚至还编译了出来：https://github.com/Admirepowered/ZygiskNext/actions/runs/7950738977

**Comment by Caribeankelp** [comment]
> > > https://github.com/Dr-TSNG/ZygiskNext/tree/master
> > > 不开源？您仔细看看
> > 
> > 
> > 我知道不开源，所以向开发者反馈，烦请原生开发者适配一下，如果开源肯定有人适配
> 
> 眼睛和脑子一定缺少一个：[https://github.com/Dr-TSNG/ZygiskNext/pull/88，而且这个](https://github.com/Dr-TSNG/ZygiskNext/pull/88%EF%BC%8C%E8%80%8C%E4%B8%94%E8%BF%99%E4%B8%AA) PR 的作者甚至还编译了出来：https://github.com/Admirepowered/ZygiskNext/actions/runs/7950738977
我觉得你的嘴是多余的，你的父母就是这样教你和别人讲话的？另外，我也没请你回复

**Comment by ShionKanagawa** [comment]
> > > > https://github.com/Dr-TSNG/ZygiskNext/tree/master
> > > > 不开源？您仔细看看
> > > 
> > > 
> > > 我知道不开源，所以向开发者反馈，烦请原生开发者适配一下，如果开源肯定有人适配
> > 
> > 
> > 眼睛和脑子一定缺少一个：[https://github.com/Dr-TSNG/ZygiskNext/pull/88，而且这个](https://github.com/Dr-TSNG/ZygiskNext/pull/88%EF%BC%8C%E8%80%8C%E4%B8%94%E8%BF%99%E4%B8%AA) PR 的作者甚至还编译了出来：https://github.com/Admirepowered/ZygiskNext/actions/runs/7950738977
> > 我觉得你的嘴是多余的，你的父母就是这样教你和别人讲话的？另外，我也没请你回复

看起来不只是没眼睛，脑子也没有，这就急眼了？兼容 Apatch 的 Release 都已经发出来了，自己不会刷，纯几把小丑🤡

**Comment by Caribeankelp** [comment]
> > > > > https://github.com/Dr-TSNG/ZygiskNext/tree/master
> > > > > 不开源？您仔细看看
> > > > 
> > > > 
> > > > 我知道不开源，所以向开发者反馈，烦请原生开发者适配一下，如果开源肯定有人适配
> > > 
> > > 
> > > 眼睛和脑子一定缺少一个：[https://github.com/Dr-TSNG/ZygiskNext/pull/88，而且这个](https://github.com/Dr-TSNG/ZygiskNext/pull/88%EF%BC%8C%E8%80%8C%E4%B8%94%E8%BF%99%E4%B8%AA) PR 的作者甚至还编译了出来：https://github.com/Admirepowered/ZygiskNext/actions/runs/7950738977
> > > 我觉得你的嘴是多余的，你的父母就是这样教你和别人讲话的？另外，我也没请你回复
> 
> 看起来不只是没眼睛，脑子也没有，这就急眼了？兼容 Apatch 的 Release 都已经发出来了，自己不会刷，纯几把小丑🤡

什么样的父母就有什么样的人，只要你同意谁先说脏话，谁死全家，我就认可你说的话

**Comment by ShionKanagawa** [comment]
> > > > > > https://github.com/Dr-TSNG/ZygiskNext/tree/master
> > > > > > 不开源？您仔细看看
> > > > > 
> > > > > 
> > > > > 我知道不开源，所以向开发者反馈，烦请原生开发者适配一下，如果开源肯定有人适配
> > > > 
> > > > 
> > > > 眼睛和脑子一定缺少一个：[https://github.com/Dr-TSNG/ZygiskNext/pull/88，而且这个](https://github.com/Dr-TSNG/ZygiskNext/pull/88%EF%BC%8C%E8%80%8C%E4%B8%94%E8%BF%99%E4%B8%AA) PR 的作者甚至还编译了出来：https://github.com/Admirepowered/ZygiskNext/actions/runs/7950738977
> > > > 我觉得你的嘴是多余的，你的父母就是这样教你和别人讲话的？另外，我也没请你回复
> > 
> > 
> > 看起来不只是没眼睛，脑子也没有，这就急眼了？兼容 Apatch 的 Release 都已经发出来了，自己不会刷，纯几把小丑🤡
> 
> 什么样的父母就有什么样的人，只要你同意谁先说脏话，谁死全家，我就认可你说的话

这就破防了？急急急急急。我觉得你户口本可能只有一页，有这个功夫早就把带着 Apatch Support 的 CI Build 给刷上了 🤡

**Comment by Caribeankelp** [comment]
> > > > > https://github.com/Dr-TSNG/ZygiskNext/tree/master
> > > > > 不开源？您仔细看看
> > > > 
> > > > 
> > > > 我知道不开源，所以向开发者反馈，烦请原生开发者适配一下，如果开源肯定有人适配
> > > 
> > > 
> > > 眼睛和脑子一定缺少一个：[https://github.com/Dr-TSNG/ZygiskNext/pull/88，而且这个](https://github.com/Dr-TSNG/ZygiskNext/pull/88%EF%BC%8C%E8%80%8C%E4%B8%94%E8%BF%99%E4%B8%AA) PR 的作者甚至还编译了出来：https://github.com/Admirepowered/ZygiskNext/actions/runs/7950738977
> > > 我觉得你的嘴是多余的，你的父母就是这样教你和别人讲话的？另外，我也没请你回复
> 
> 看起来不只是没眼睛，脑子也没有，这就急眼了？兼容 Apatch 的 Release 都已经发出来了，自己不会刷，纯几把小丑🤡

骂人就是骂人了，和怂包一样不敢承认，我可没请你回复，自己嘴贱，上来呈脸给我骂，你确实挺犯贱的，哈哈哈哈

**Comment by ShionKanagawa** [comment]
> > > > > > https://github.com/Dr-TSNG/ZygiskNext/tree/master
> > > > > > 不开源？您仔细看看
> > > > > 
> > > > > 
> > > > > 我知道不开源，所以向开发者反馈，烦请原生开发者适配一下，如果开源肯定有人适配
> > > > 
> > > > 
> > > > 眼睛和脑子一定缺少一个：[https://github.com/Dr-TSNG/ZygiskNext/pull/88，而且这个](https://github.com/Dr-TSNG/ZygiskNext/pull/88%EF%BC%8C%E8%80%8C%E4%B8%94%E8%BF%99%E4%B8%AA) PR 的作者甚至还编译了出来：https://github.com/Admirepowered/ZygiskNext/actions/runs/7950738977
> > > > 我觉得你的嘴是多余的，你的父母就是这样教你和别人讲话的？另外，我也没请你回复
> > 
> > 
> > 看起来不只是没眼睛，脑子也没有，这就急眼了？兼容 Apatch 的 Release 都已经发出来了，自己不会刷，纯几把小丑🤡
> 
> 骂人就是骂人了，和怂包一样不敢承认，我可没请你回复，自己嘴贱，上来呈脸给我骂，你确实挺犯贱的，哈哈哈哈

难绷，我可能骂的不是个人捏，是没有眼睛和脑子的伪人捏。自己脑子没长还怪别人，属实难绷

**Comment by Caribeankelp** [comment]
> > > > > > > https://github.com/Dr-TSNG/ZygiskNext/tree/master
> > > > > > > 不开源？您仔细看看
> > > > > > 
> > > > > > 
> > > > > > 我知道不开源，所以向开发者反馈，烦请原生开发者适配一下，如果开源肯定有人适配
> > > > > 
> > > > > 
> > > > > 眼睛和脑子一定缺少一个：[https://github.com/Dr-TSNG/ZygiskNext/pull/88，而且这个](https://github.com/Dr-TSNG/ZygiskNext/pull/88%EF%BC%8C%E8%80%8C%E4%B8%94%E8%BF%99%E4%B8%AA) PR 的作者甚至还编译了出来：https://github.com/Admirepowered/ZygiskNext/actions/runs/7950738977
> > > > > 我觉得你的嘴是多余的，你的父母就是这样教你和别人讲话的？另外，我也没请你回复
> > > 
> > > 
> > > 看起来不只是没眼睛，脑子也没有，这就急眼了？兼容 Apatch 的 Release 都已经发出来了，自己不会刷，纯几把小丑🤡
> > 
> > 
> > 什么样的父母就有什么样的人，只要你同意谁先说脏话，谁死全家，我就认可你说的话
> 
> 这就破防了？急急急急急。我觉得你户口本可能只有一页，有这个功夫早就把带着 Apatch Support 的 CI Build 给刷上了 🤡

既然你不否认谁先骂人谁死全家，我就默认你同意了。反正你也不在乎，我只知道谁先骂人谁死全家

**Comment by Caribeankelp** [comment]
> > > > > > > > https://github.com/Dr-TSNG/ZygiskNext/tree/master
> > > > > > > > 不开源？您仔细看看
> > > > > > > 
> > > > > > > 
> > > > > > > 我知道不开源，所以向开发者反馈，烦请原生开发者适配一下，如果开源肯定有人适配
> > > > > > 
> > > > > > 
> > > > > > 眼睛和脑子一定缺少一个：[https://github.com/Dr-TSNG/ZygiskNext/pull/88，而且这个](https://github.com/Dr-TSNG/ZygiskNext/pull/88%EF%BC%8C%E8%80%8C%E4%B8%94%E8%BF%99%E4%B8%AA) PR 的作者甚至还编译了出来：https://github.com/Admirepowered/ZygiskNext/actions/runs/7950738977
> > > > > > 我觉得你的嘴是多余的，你的父母就是这样教你和别人讲话的？另外，我也没请你回复
> > > > 
> > > > 
> > > > 看起来不只是没眼睛，脑子也没有，这就急眼了？兼容 Apatch 的 Release 都已经发出来了，自己不会刷，纯几把小丑🤡
> > > 
> > > 
> > > 什么样的父母就有什么样的人，只要你同意谁先说脏话，谁死全家，我就认可你说的话
> > 
> > 
> > 这就破防了？急急急急急。我觉得你户口本可能只有一页，有这个功夫早就把带着 Apatch Support 的 CI Build 给刷上了 🤡
> 
> 既然你不否认谁先骂人谁死全家，我就默认你同意了。反正你也不在乎，我只知道谁先骂人谁死全家

谁先骂人谁死全家

**Comment by woshishabii** [comment]
合影🤣

**Comment by Caribeankelp** [comment]
> > > > > > > https://github.com/Dr-TSNG/ZygiskNext/tree/master
> > > > > > > 不开源？您仔细看看
> > > > > > 
> > > > > > 
> > > > > > 我知道不开源，所以向开发者反馈，烦请原生开发者适配一下，如果开源肯定有人适配
> > > > > 
> > > > > 
> > > > > 眼睛和脑子一定缺少一个：[https://github.com/Dr-TSNG/ZygiskNext/pull/88，而且这个](https://github.com/Dr-TSNG/ZygiskNext/pull/88%EF%BC%8C%E8%80%8C%E4%B8%94%E8%BF%99%E4%B8%AA) PR 的作者甚至还编译了出来：https://github.com/Admirepowered/ZygiskNext/actions/runs/7950738977
> > > > > 我觉得你的嘴是多余的，你的父母就是这样教你和别人讲话的？另外，我也没请你回复
> > > 
> > > 
> > > 看起来不只是没眼睛，脑子也没有，这就急眼了？兼容 Apatch 的 Release 都已经发出来了，自己不会刷，纯几把小丑🤡
> > 
> > 
> > 骂人就是骂人了，和怂包一样不敢承认，我可没请你回复，自己嘴贱，上来呈脸给我骂，你确实挺犯贱的，哈哈哈哈
> 
> 难绷，我可能骂的不是个人捏，是没有眼睛和脑子的伪人捏。自己脑子没长还怪别人，属实难绷

傻逼骂谁？

**Comment by Caribeankelp** [comment]
> > > > > > > > https://github.com/Dr-TSNG/ZygiskNext/tree/master
> > > > > > > > 不开源？您仔细看看
> > > > > > > 
> > > > > > > 
> > > > > > > 我知道不开源，所以向开发者反馈，烦请原生开发者适配一下，如果开源肯定有人适配
> > > > > > 
> > > > > > 
> > > > > > 眼睛和脑子一定缺少一个：[https://github.com/Dr-TSNG/ZygiskNext/pull/88，而且这个](https://github.com/Dr-TSNG/ZygiskNext/pull/88%EF%BC%8C%E8%80%8C%E4%B8%94%E8%BF%99%E4%B8%AA) PR 的作者甚至还编译了出来：https://github.com/Admirepowered/ZygiskNext/actions/runs/7950738977
> > > > > > 我觉得你的嘴是多余的，你的父母就是这样教你和别人讲话的？另外，我也没请你回复
> > > > 
> > > > 
> > > > 看起来不只是没眼睛，脑子也没有，这就急眼了？兼容 Apatch 的 Release 都已经发出来了，自己不会刷，纯几把小丑🤡
> > > 
> > > 
> > > 什么样的父母就有什么样的人，只要你同意谁先说脏话，谁死全家，我就认可你说的话
> > 
> > 
> > 这就破防了？急急急急急。我觉得你户口本可能只有一页，有这个功夫早就把带着 Apatch Support 的 CI Build 给刷上了 🤡
> 
> 既然你不否认谁先骂人谁死全家，我就默认你同意了。反正你也不在乎，我只知道谁先骂人谁死全家

只要你认同自己是傻逼，谁先骂人谁死全家，你可以继续回复，我不拦着，下面请傻逼继续发言，哈哈哈哈哈

**Comment by shadow3aaa** [comment]
> > > > https://github.com/Dr-TSNG/ZygiskNext/tree/master
> > > > 不开源？您仔细看看
> > > 
> > > 
> > > 我知道不开源，所以向开发者反馈，烦请原生开发者适配一下，如果开源肯定有人适配
> > 
> > 眼睛和脑子一定缺少一个：[https://github.com/Dr-TSNG/ZygiskNext/pull/88，而且这个](https://github.com/Dr-TSNG/ZygiskNext/pull/88%EF%BC%8C%E8%80%8C%E4%B8%94%E8%BF%99%E4%B8%AA) PR 的作者甚至还编译了出来：https://github.com/Admirepowered/ZygiskNext/actions/runs/7950738977
> 我觉得你的嘴是多余的，你的父母就是这样教你和别人讲话的？另外，我也没请你回复

你是🤡吗，还给自己精神胜利法起来了

**Comment by Caribeankelp** [comment]
> > > > > https://github.com/Dr-TSNG/ZygiskNext/tree/master
> > > > > 不开源？您仔细看看
> > > > 
> > > > 
> > > > 我知道不开源，所以向开发者反馈，烦请原生开发者适配一下，如果开源肯定有人适配
> > > 
> > > 
> > > 眼睛和脑子一定缺少一个：[https://github.com/Dr-TSNG/ZygiskNext/pull/88，而且这个](https://github.com/Dr-TSNG/ZygiskNext/pull/88%EF%BC%8C%E8%80%8C%E4%B8%94%E8%BF%99%E4%B8%AA) PR 的作者甚至还编译了出来：https://github.com/Admirepowered/ZygiskNext/actions/runs/7950738977
> > > 我觉得你的嘴是多余的，你的父母就是这样教你和别人讲话的？另外，我也没请你回复
> 
> 你是🤡吗，还给自己精神胜利法起来了

我只知道谁先骂人谁死全家，反正你又没否认你骂人就行，还有，什么时候请你回复了，再说了，你发的链接我不想看，我看不看是我的事

**Comment by armv7a** [comment]
> > > https://github.com/Dr-TSNG/ZygiskNext/tree/master
> > > 不开源？您仔细看看
> > 
> > 
> > 我知道不开源，所以向开发者反馈，烦请原生开发者适配一下，如果开源肯定有人适配
> 
> 眼睛和脑子一定缺少一个：[https://github.com/Dr-TSNG/ZygiskNext/pull/88，而且这个](https://github.com/Dr-TSNG/ZygiskNext/pull/88%EF%BC%8C%E8%80%8C%E4%B8%94%E8%BF%99%E4%B8%AA) PR 的作者甚至还编译了出来：https://github.com/Admirepowered/ZygiskNext/actions/runs/7950738977

我觉得当时您的回答有些过激。
根据楼主的issue我觉得他的原意是这样的：
在后续更新的版本中由于闭源的原因用户无法自行去适配所使用的工具，所以楼主在请求开发者能否加入 Apatch 的适配而且还可以获得后续的“更新”。

**Comment by Caribeankelp** [comment]
> > > > https://github.com/Dr-TSNG/ZygiskNext/tree/master
> > > > 不开源？您仔细看看
> > > 
> > > 
> > > 我知道不开源，所以向开发者反馈，烦请原生开发者适配一下，如果开源肯定有人适配
> > 
> > 
> > 眼睛和脑子一定缺少一个：[https://github.com/Dr-TSNG/ZygiskNext/pull/88，而且这个](https://github.com/Dr-TSNG/ZygiskNext/pull/88%EF%BC%8C%E8%80%8C%E4%B8%94%E8%BF%99%E4%B8%AA) PR 的作者甚至还编译了出来：https://github.com/Admirepowered/ZygiskNext/actions/runs/7950738977
> 
> 我觉得当时您的回答有些过激。 根据楼主的issue我觉得他的原意是这样的： 在后续更新的版本中由于闭源的原因用户无法自行去适配所使用的工具，所以楼主在请求开发者能否加入 Apatch 的适配而且还可以获得后续的“更新”。

是的，我就这个意思，这人上来就喷，属实一个网络喷子，其实本质上还是希望原开发者原生支持apatch

**Comment by OrStudio** [comment]
> > > > > https://github.com/Dr-TSNG/ZygiskNext/tree/master
> > > > > 不开源？您仔细看看
> > > > 
> > > > 
> > > > 我知道不开源，所以向开发者反馈，烦请原生开发者适配一下，如果开源肯定有人适配
> > > 
> > > 
> > > 眼睛和脑子一定缺少一个：[https://github.com/Dr-TSNG/ZygiskNext/pull/88，而且这个](https://github.com/Dr-TSNG/ZygiskNext/pull/88%EF%BC%8C%E8%80%8C%E4%B8%94%E8%BF%99%E4%B8%AA) PR 的作者甚至还编译了出来：https://github.com/Admirepowered/ZygiskNext/actions/runs/7950738977
> > 
> > 
> > 我觉得当时您的回答有些过激。 根据楼主的issue我觉得他的原意是这样的： 在后续更新的版本中由于闭源的原因用户无法自行去适配所使用的工具，所以楼主在请求开发者能否加入 Apatch 的适配而且还可以获得后续的“更新”。
> 
> 是的，我就这个意思，这人上来就喷，属实一个网络喷子，其实本质上还是希望原开发者原生支持apatch

Have you searched for APatch in this repository before making any requests?
You'll find some amazing things, and maybe that's why the developers don't want to support APatch at the moment.
There is already a PR that adds support for APatch, but for some reason APatch's logic is inconsistent with KernelSU and Magisk, so the PR won't be merged at this time.

**Comment by OrStudio** [comment]
You should stop, the developers have publicly stated many times that APatch will not be supported at this time. Repeatedly asking will only make the developers more annoyed and cause the likelihood of support to drop dramatically.

**Comment by DuckDeng** [comment]
> > > https://github.com/Dr-TSNG/ZygiskNext/tree/master
> > > 不开源？您仔细看看
> > 
> > 
> > 我知道不开源，所以向开发者反馈，烦请原生开发者适配一下，如果开源肯定有人适配
> 
> 眼睛和脑子一定缺少一个：[https://github.com/Dr-TSNG/ZygiskNext/pull/88，而且这个](https://github.com/Dr-TSNG/ZygiskNext/pull/88%EF%BC%8C%E8%80%8C%E4%B8%94%E8%BF%99%E4%B8%AA) PR 的作者甚至还编译了出来：https://github.com/Admirepowered/ZygiskNext/actions/runs/7950738977

楼主在提问前确实没有充分查阅，但您完全可以更礼貌些的指出问题。确实有一个pr添加了功能，但他的意思可能是后续版本的更新问题。过激的语言不利于解决问题

**Comment by Mooling0602** [comment]
Please close this issue and ask everyone to discuss this topic more rationally and peacefully.
请关闭这个issue，并烦请各位更理性平和的讨论问题。
个人认为GitHub不适合作为一个用来吵架的地方。

**Comment by armv7a** [comment]
ZygiskNext 那边已经适配了，应该可以 Close 掉这个 Issue 了
