### ISSUE TITLE
[BUG] 模块未生效

### ISSUE THREAD

**Issue by hnuuhc** [Dr-TSNG/ZygiskOnKernelSU#9]
设备: mix2s
系统: PE13Plus
内核版本: 4.9.337-Etude-Op.13-No.2-g323378b4-dirty
安卓版本: 13
kernelsu版本: 10657
管理器版本: 10651

已经试过所有模块版本,模块均未生效,以下是电脑adb抓取的开机日志
[log.zip](https://github.com/Dr-TSNG/ZygiskOnKernelSU/files/10835632/log.zip)

**Comment by Dr-TSNG** [comment]
843086f6f365df29aea99f0a9e090a40e507bfc4
