### ISSUE TITLE
ZygiskNext is being detected.

### ISSUE THREAD

**Issue by ItsMadruga** [Dr-TSNG/ZygiskOnKernelSU#90]
I use KernelSu to root my device, and I use this module, but it is being detected by my banking application (Inter&Co).To use it, I have to deactivate and restart my device, which is not feasible to do every time I use the bank.

Please help, I use shamiko to try to hide it, but it is still being detected

Thank you for your attention

**Comment by Dr-TSNG** [comment]
![Screenshot_2024-02-24-13-23-23-984_com miui home](https://github.com/Dr-TSNG/ZygiskNext/assets/52071314/ad532410-182e-4c61-9492-eb74836685cc)

**Comment by ItsMadruga** [comment]
![Screenshot_20240224_095658_One UI Home](https://github.com/Dr-TSNG/ZygiskNext/assets/104334266/c8da825f-08e1-49d2-9a33-332bf58f0527)

**Comment by OrStudio** [comment]
![Screenshot_20240224-210848](https://github.com/Dr-TSNG/ZygiskNext/assets/1701912/28593bca-1cce-4e51-9729-b26e689d82ac)
normal work

**Comment by ItsMadruga** [comment]
> ![Screenshot_20240224-210848](https://private-user-images.githubusercontent.com/1701912/307523946-28593bca-1cce-4e51-9729-b26e689d82ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3ODA5OTMsIm5iZiI6MTcwODc4MDY5MywicGF0aCI6Ii8xNzAxOTEyLzMwNzUyMzk0Ni0yODU5M2JjYS0xY2NlLTRlNTEtOTcyOS1iMjZlNjg5ZDgyYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjRUMTMxODEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmYyNWNmNGQ4N2ZkMGFhNjRkMDZmNjQ1MzI3YzBlM2IzNGEyZjMwOTBmZTlkNDJjY2NkMjc3Y2VjZjkwN2Q2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D8cVyDdGIQ1kaCyWKw3GG-jb4PDffg2WUI4AHsjQT7Y) normal work

but for me it's not working.

**Comment by OrStudio** [comment]
> > ![Screenshot_20240224-210848](https://private-user-images.githubusercontent.com/1701912/307523946-28593bca-1cce-4e51-9729-b26e689d82ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3ODA5OTMsIm5iZiI6MTcwODc4MDY5MywicGF0aCI6Ii8xNzAxOTEyLzMwNzUyMzk0Ni0yODU5M2JjYS0xY2NlLTRlNTEtOTcyOS1iMjZlNjg5ZDgyYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjRUMTMxODEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmYyNWNmNGQ4N2ZkMGFhNjRkMDZmNjQ1MzI3YzBlM2IzNGEyZjMwOTBmZTlkNDJjY2NkMjc3Y2VjZjkwN2Q2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D8cVyDdGIQ1kaCyWKw3GG-jb4PDffg2WUI4AHsjQT7Y) normal work
> 
> but for me it's not working.

You should check your device environment and make sure the device environment is clean before testing. In addition, this is not the repository for shamiko to report problems. Please go to the LSPosed discussion group to report them.

**Comment by ItsMadruga** [comment]
> > > ![Screenshot_20240224-210848](https://private-user-images.githubusercontent.com/1701912/307523946-28593bca-1cce-4e51-9729-b26e689d82ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3ODA5OTMsIm5iZiI6MTcwODc4MDY5MywicGF0aCI6Ii8xNzAxOTEyLzMwNzUyMzk0Ni0yODU5M2JjYS0xY2NlLTRlNTEtOTcyOS1iMjZlNjg5ZDgyYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjRUMTMxODEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmYyNWNmNGQ4N2ZkMGFhNjRkMDZmNjQ1MzI3YzBlM2IzNGEyZjMwOTBmZTlkNDJjY2NkMjc3Y2VjZjkwN2Q2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D8cVyDdGIQ1kaCyWKw3GG-jb4PDffg2WUI4AHsjQT7Y) normal work
> > 
> > 
> > but for me it's not working.
> 
> You should check your device environment and make sure the device environment is clean before testing. In addition, this is not the repository for shamiko to report problems. Please go to the LSPosed discussion group to report them.

Firstly, I didn't say that the problem is with shamiko, but with the ZygiskNext module, as the presence of shamiko didn't make any difference, and yes, when the ZygiskNext module is deactivated the application works perfectly, so the problem is in the module, yes my device is completely clean and everything works perfectly. I ask that you read more carefully before talking about things you don't know. Thanks.

**Comment by OrStudio** [comment]
> > > > ![Screenshot_20240224-210848](https://private-user-images.githubusercontent.com/1701912/307523946-28593bca-1cce-4e51-9729-b26e689d82ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3ODA5OTMsIm5iZiI6MTcwODc4MDY5MywicGF0aCI6Ii8xNzAxOTEyLzMwNzUyMzk0Ni0yODU5M2JjYS0xY2NlLTRlNTEtOTcyOS1iMjZlNjg5ZDgyYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjRUMTMxODEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmYyNWNmNGQ4N2ZkMGFhNjRkMDZmNjQ1MzI3YzBlM2IzNGEyZjMwOTBmZTlkNDJjY2NkMjc3Y2VjZjkwN2Q2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D8cVyDdGIQ1kaCyWKw3GG-jb4PDffg2WUI4AHsjQT7Y) normal work
> > > 
> > > 
> > > but for me it's not working.
> > 
> > 
> > You should check your device environment and make sure the device environment is clean before testing. In addition, this is not the repository for shamiko to report problems. Please go to the LSPosed discussion group to report them.
> 
> Firstly, I didn't say that the problem is with shamiko, but with the ZygiskNext module, as the presence of shamiko didn't make any difference, and yes, when the ZygiskNext module is deactivated the application works perfectly, so the problem is in the module, yes my device is completely clean and everything works perfectly. I ask that you read more carefully before talking about things you don't know. Thanks.

So congratulations, two people have already proved that there is no problem

**Comment by ItsMadruga** [comment]
> > > > > ![Screenshot_20240224-210848](https://private-user-images.githubusercontent.com/1701912/307523946-28593bca-1cce-4e51-9729-b26e689d82ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3ODA5OTMsIm5iZiI6MTcwODc4MDY5MywicGF0aCI6Ii8xNzAxOTEyLzMwNzUyMzk0Ni0yODU5M2JjYS0xY2NlLTRlNTEtOTcyOS1iMjZlNjg5ZDgyYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjRUMTMxODEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmYyNWNmNGQ4N2ZkMGFhNjRkMDZmNjQ1MzI3YzBlM2IzNGEyZjMwOTBmZTlkNDJjY2NkMjc3Y2VjZjkwN2Q2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D8cVyDdGIQ1kaCyWKw3GG-jb4PDffg2WUI4AHsjQT7Y) normal work
> > > > 
> > > > 
> > > > but for me it's not working.
> > > 
> > > 
> > > You should check your device environment and make sure the device environment is clean before testing. In addition, this is not the repository for shamiko to report problems. Please go to the LSPosed discussion group to report them.
> > 
> > 
> > Firstly, I didn't say that the problem is with shamiko, but with the ZygiskNext module, as the presence of shamiko didn't make any difference, and yes, when the ZygiskNext module is deactivated the application works perfectly, so the problem is in the module, yes my device is completely clean and everything works perfectly. I ask that you read more carefully before talking about things you don't know. Thanks.
> 
> So congratulations, two people have already proved that there is no problem

So just because 2 people don't have the problem, the right thing to do is just ignore it?

**Comment by OrStudio** [comment]
> > > > > > ![Screenshot_20240224-210848](https://private-user-images.githubusercontent.com/1701912/307523946-28593bca-1cce-4e51-9729-b26e689d82ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3ODA5OTMsIm5iZiI6MTcwODc4MDY5MywicGF0aCI6Ii8xNzAxOTEyLzMwNzUyMzk0Ni0yODU5M2JjYS0xY2NlLTRlNTEtOTcyOS1iMjZlNjg5ZDgyYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjRUMTMxODEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmYyNWNmNGQ4N2ZkMGFhNjRkMDZmNjQ1MzI3YzBlM2IzNGEyZjMwOTBmZTlkNDJjY2NkMjc3Y2VjZjkwN2Q2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D8cVyDdGIQ1kaCyWKw3GG-jb4PDffg2WUI4AHsjQT7Y) normal work
> > > > > 
> > > > > 
> > > > > but for me it's not working.
> > > > 
> > > > 
> > > > You should check your device environment and make sure the device environment is clean before testing. In addition, this is not the repository for shamiko to report problems. Please go to the LSPosed discussion group to report them.
> > > 
> > > 
> > > Firstly, I didn't say that the problem is with shamiko, but with the ZygiskNext module, as the presence of shamiko didn't make any difference, and yes, when the ZygiskNext module is deactivated the application works perfectly, so the problem is in the module, yes my device is completely clean and everything works perfectly. I ask that you read more carefully before talking about things you don't know. Thanks.
> > 
> > 
> > So congratulations, two people have already proved that there is no problem
> 
> So just because 2 people don't have the problem, the right thing to do is just ignore it?

In addition, ZygiskNextˉ does not provide any hidden functions, so it is normal to be detected. ZygiskNext should not be detected when Shamiko is turned on, so I would say it is a problem with your device environment.

**Comment by ItsMadruga** [comment]
> > > > > > > ![Screenshot_20240224-210848](https://private-user-images.githubusercontent.com/1701912/307523946-28593bca-1cce-4e51-9729-b26e689d82ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3ODA5OTMsIm5iZiI6MTcwODc4MDY5MywicGF0aCI6Ii8xNzAxOTEyLzMwNzUyMzk0Ni0yODU5M2JjYS0xY2NlLTRlNTEtOTcyOS1iMjZlNjg5ZDgyYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjRUMTMxODEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmYyNWNmNGQ4N2ZkMGFhNjRkMDZmNjQ1MzI3YzBlM2IzNGEyZjMwOTBmZTlkNDJjY2NkMjc3Y2VjZjkwN2Q2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D8cVyDdGIQ1kaCyWKw3GG-jb4PDffg2WUI4AHsjQT7Y) normal work
> > > > > > 
> > > > > > 
> > > > > > but for me it's not working.
> > > > > 
> > > > > 
> > > > > You should check your device environment and make sure the device environment is clean before testing. In addition, this is not the repository for shamiko to report problems. Please go to the LSPosed discussion group to report them.
> > > > 
> > > > 
> > > > Firstly, I didn't say that the problem is with shamiko, but with the ZygiskNext module, as the presence of shamiko didn't make any difference, and yes, when the ZygiskNext module is deactivated the application works perfectly, so the problem is in the module, yes my device is completely clean and everything works perfectly. I ask that you read more carefully before talking about things you don't know. Thanks.
> > > 
> > > 
> > > So congratulations, two people have already proved that there is no problem
> > 
> > 
> > So just because 2 people don't have the problem, the right thing to do is just ignore it?
> 
> In addition, ZygiskNextˉ does not provide any hidden functions, so it is normal to be detected. ZygiskNext should not be detected when Shamiko is turned on, so I would say it is a problem with your device environment.

Since the problem is in my device's environment, if when ZygiskNext is disabled, the application works normally?

**Comment by OrStudio** [comment]
> > > > > > > > ![Screenshot_20240224-210848](https://private-user-images.githubusercontent.com/1701912/307523946-28593bca-1cce-4e51-9729-b26e689d82ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3ODA5OTMsIm5iZiI6MTcwODc4MDY5MywicGF0aCI6Ii8xNzAxOTEyLzMwNzUyMzk0Ni0yODU5M2JjYS0xY2NlLTRlNTEtOTcyOS1iMjZlNjg5ZDgyYWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjRUMTMxODEzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmYyNWNmNGQ4N2ZkMGFhNjRkMDZmNjQ1MzI3YzBlM2IzNGEyZjMwOTBmZTlkNDJjY2NkMjc3Y2VjZjkwN2Q2NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D8cVyDdGIQ1kaCyWKw3GG-jb4PDffg2WUI4AHsjQT7Y) normal work
> > > > > > > 
> > > > > > > 
> > > > > > > but for me it's not working.
> > > > > > 
> > > > > > 
> > > > > > You should check your device environment and make sure the device environment is clean before testing. In addition, this is not the repository for shamiko to report problems. Please go to the LSPosed discussion group to report them.
> > > > > 
> > > > > 
> > > > > Firstly, I didn't say that the problem is with shamiko, but with the ZygiskNext module, as the presence of shamiko didn't make any difference, and yes, when the ZygiskNext module is deactivated the application works perfectly, so the problem is in the module, yes my device is completely clean and everything works perfectly. I ask that you read more carefully before talking about things you don't know. Thanks.
> > > > 
> > > > 
> > > > So congratulations, two people have already proved that there is no problem
> > > 
> > > 
> > > So just because 2 people don't have the problem, the right thing to do is just ignore it?
> > 
> > 
> > In addition, ZygiskNextˉ does not provide any hidden functions, so it is normal to be detected. ZygiskNext should not be detected when Shamiko is turned on, so I would say it is a problem with your device environment.
> 
> Since the problem is in my device's environment, if when ZygiskNext is disabled, the application works normally?

So according to your logic, Shamiko is the origin of the problem. As I said, ZygiskNext does not contain any hidden functions. If it works normally if you turn it off, then the problem is caused by improper hiding of Shamiko, so this problem is not Handled by ZygiskNext

**Comment by JasonKhew96** [comment]
I didn't even turn on umount for this app, which means Shamiko will not hide anything.

![Screenshot_20240224-221835.png](https://github.com/Dr-TSNG/ZygiskNext/assets/29531167/b57cc98b-2233-422c-b84c-02beb2836834)

**Comment by JasonKhew96** [comment]
turn off any zygisk module (lsposed) and retry

**Comment by Wojtaz0w** [comment]
Try disabling LSPosed logs, they generally make it easy to detect.

**Comment by OrStudio** [comment]
> Try disabling LSPosed logs, they generally make it easy to detect.

Are you mentally retarded?If it is a log issue, others will be detected as well.
