### ISSUE TITLE
Flashing from platform tool cmd

### ISSUE THREAD

**Issue by Subnotpab** [Dr-TSNG/ZygiskOnKernelSU#92]
Can I flash this zip from cmd ? Because zygisk   shows "NO" in magisk even after flashing the patched image,I do get root but not the root management in magisk which is not allowing me to use root permission

**Comment by Dr-TSNG** [comment]
`magisk --install-module /data/local/tmp/module.zip`

**Comment by Subnotpab** [comment]
Do this in cmm from platform tool?

**Comment by Dr-TSNG** [comment]
adb shell

**Comment by Subnotpab** [comment]
Alr I will try , thanks

**Comment by Subnotpab** [comment]
Do I need to stay in fastboot mode before doing this, sorry I don't wanna cause any problems

**Comment by Dr-TSNG** [comment]
No

**Comment by Subnotpab** [comment]
![IMG20240301213535](https://github.com/Dr-TSNG/ZygiskNext/assets/135521522/589fee98-fe60-4328-b010-8fd84679f69b)
Hmm?

**Comment by Dr-TSNG** [comment]
You should learn basic use of adb. Here is not kindergarten.

**Comment by Subnotpab** [comment]
😭 I just know the adb reboot bootloader,adb device, fastboot flash boot and some common ones, because it always worked 
![Screenshot_2024-03-01-21-23-16-00_785cfb1f0fb0c9a2030c9b38a1c3479a](https://github.com/Dr-TSNG/ZygiskNext/assets/135521522/0c357910-185d-4f52-8c0d-221726d33dd9)
![Screenshot_2024-03-01-22-02-28-53_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Dr-TSNG/ZygiskNext/assets/135521522/52879814-a194-4e6d-a06c-fc508cf1f162)
,maybe this can help understand my problem better

**Comment by Subnotpab** [comment]
I just want my zygisk to work man,if u help this poor soul

**Comment by Subnotpab** [comment]
Never happened before btw

**Comment by Subnotpab** [comment]
Figured it out,tho it says to me run this command with root
