### ISSUE TITLE
Module files corrupted error

### ISSUE THREAD

**Issue by kgursu** [Dr-TSNG/ZygiskOnKernelSU#93]
I can see that error on KernelSU modules page:
![Screenshot_20240301-224019_1.png](https://github.com/Dr-TSNG/ZygiskNext/assets/35314872/5bdb2d00-65e2-4152-b8ca-435639d54041)

Installed latest KernelSU 0.8.1-20-gdbe43b1 (11583).

Logs: ![bootlog-2024-03-01-22-35-07.tar.gz](https://github.com/Dr-TSNG/ZygiskNext/files/14465298/bootlog-2024-03-01-22-35-07.tar.gz)

![KernelSU_bugreport_2024-03-01_22_41.tar.gz](https://github.com/Dr-TSNG/ZygiskNext/files/14465300/KernelSU_bugreport_2024-03-01_22_41.tar.gz)

**Comment by Unlearned6688** [comment]
Mine also corrupted (same message. Pixel 6a running Pixel OS, Feb 2024 Android 14)

I uninstalled Zygisk, re-installed most up to date (same as before), reboot, now it doesn't show corrupted. I'm assuming kernelSU corrupted something when updating, but who knows

**Comment by DoulosTrieste** [comment]
> Mine also corrupted (same message. Pixel 6a running Pixel OS, Feb 2024 Android 14)
> 
> I uninstalled Zygisk, re-installed most up to date (same as before), reboot, now it doesn't show corrupted. I'm assuming kernelSU corrupted something when updating, but who knows

How did you manage to uninstall? That process seems to hang on my device (Poco F1 EvoX A14 latest).

**Comment by 5ec1cff** [comment]
This is a KernelSU problem and may occur when upgrading the module image format. You can reinstall corrupted modules to fix them.

See also: https://t.me/real5ec1cff/149
