### ISSUE TITLE
The capacity recognition issue encountered in ZygiskNEXT v1.0.1 on MIUI14 Android13.And the mounting abnormality issue with Shamiko.

### ISSUE THREAD

**Issue by ShokuhouMisaki** [Dr-TSNG/ZygiskOnKernelSU#95]
In ZygiskNEXT version 0.9, Shamiko works fine, with no abnormalities in partition capacity recognition. 
However, when I updated to ZygiskNEXT v1.0.1 via KernelSU, the capacity display in my settings was expanded fourfold, and Shamiko showed mounting failure.
After removing ZygiskNEXT v1.0.1, the capacity recognition issue still cannot be resolved.
![6C4AB2DBBFE9B55DF580AE65712AB5B8](https://github.com/Dr-TSNG/ZygiskNext/assets/64940476/64eab0d7-991c-44b8-bf24-85a3410ec311)
![6815D423A8735E76D4800E07AF908481](https://github.com/Dr-TSNG/ZygiskNext/assets/64940476/c60a4879-220e-425e-91e1-ef3399a18e4e)
![C7464ECCA0A067A1A65E36F4C1D22C23](https://github.com/Dr-TSNG/ZygiskNext/assets/64940476/eaeae536-4390-4c17-9265-48300af23fee)
This is my tablet, running on MIUI14 based on Android13, with a system version of MIUI Pad 14.0.6, and a processor of 8+G1.
![DE7BAAC2FC30B76DBD0041F2C4C8BA2C](https://github.com/Dr-TSNG/ZygiskNext/assets/64940476/523ea790-5f80-41f8-abca-3173df398ce0)
![3DAFB5BE938590E22FC6DC4CF817CF85](https://github.com/Dr-TSNG/ZygiskNext/assets/64940476/008e3b27-77a6-411d-8985-0d22c022eaf5)
![596D0F836DDC24C5DC34726F0D86169A](https://github.com/Dr-TSNG/ZygiskNext/assets/64940476/71369f44-3905-4546-a86a-11f9e410d9bd)
![1DF0D14C4941186E89FD8321B57F3100](https://github.com/Dr-TSNG/ZygiskNext/assets/64940476/61c6a748-d11f-4432-a2af-5dfba5828e69)
![11](https://github.com/Dr-TSNG/ZygiskNext/assets/64940476/8cb28266-4fe2-4c91-a77c-10da39fbdd87)
![22](https://github.com/Dr-TSNG/ZygiskNext/assets/64940476/e0d92ae8-fa60-43dc-9a7a-f74237f38a30)
This is my phone, also running on MIUI14 based on Android13, with a system version of MIUI 14.0.2, and a processor of 865. Additionally, after removing the module, the capacity recognition cannot be restored to normal.

**Comment by ShokuhouMisaki** [comment]
This is the KernelSU plugin used on my phone.
![22](https://github.com/Dr-TSNG/ZygiskNext/assets/64940476/2f00e83d-5d31-45a4-ba11-9a832e6179af)
![222](https://github.com/Dr-TSNG/ZygiskNext/assets/64940476/3543aa53-f3c0-4cc5-a520-d6d8fe3d0aed)
![2222](https://github.com/Dr-TSNG/ZygiskNext/assets/64940476/53d416d7-c457-4d43-9119-a6e64f116398)
![22222](https://github.com/Dr-TSNG/ZygiskNext/assets/64940476/0e6b12b6-329a-48b2-a1e6-319299ba7604)
This is the KernelSU plugin used on my tablet.
![33](https://github.com/Dr-TSNG/ZygiskNext/assets/64940476/affa72ac-0c53-4235-8f27-962c224a09c1)
![333](https://github.com/Dr-TSNG/ZygiskNext/assets/64940476/e001ad9c-a11d-4044-947e-7ec5bc8d4bb1)

**Comment by 5ec1cff** [comment]
何意味
