### ISSUE TITLE
Dark WebUI not working

### ISSUE THREAD

**Issue by brian6932** [Dr-TSNG/ZygiskOnKernelSU#96]
Regarding `1.0.2`'s `WebUI follows the system dark theme setting`.
Doesn't matter whether stock WebView's used or a different one.
![](https://github.com/Dr-TSNG/ZygiskNext/assets/18603393/a3b52e2d-c406-4b7d-b08c-ae05bbe766bc)
![](https://github.com/Dr-TSNG/ZygiskNext/assets/18603393/d10b1635-fafc-4168-9dc8-b6f8f348f2f1)

Phone: Zenfone 9
ROM: omni-14-202403121645-zenfone9-GAPPS

**Comment by 5ec1cff** [comment]
Please install CI Manager [11703](https://github.com/tiann/KernelSU/actions/runs/8406546942) or higher
