### ISSUE TITLE
Zygisk qpr2 not working

### ISSUE THREAD

**Issue by thomasdmuc** [Dr-TSNG/ZygiskOnKernelSU#97]
Dear sir,

I believe you need to implement the following in order to make zygisk working in qpr2

[Zygisk] Introduce new code injection mechanism
[Zygisk] Support new signature introduced in U QPR2

Kind regards

**Comment by thomasdmuc** [comment]
It appears to me that it is not working yet on qpr2? I am sorry but for the time being I cannot collect any traces to help diagnosing it.

**Comment by wzgrx** [comment]
+1

**Comment by 5ec1cff** [comment]
Invalid report
