### ISSUE TITLE
升级1.04版本，lsp失效打不开，降级到1.03版本，next模块报错，卸载next模块重新安装还是报错，旧版本无法使用，手机无限重启

### ISSUE THREAD

**Issue by wzgrx** [Dr-TSNG/ZygiskOnKernelSU#98]
使用ksu，没有升级系统其他任何操作
[❌ Stop inject zygote due to crash. Root: KernelSU] Standalone implementation of Zygisk.

**Comment by 5ec1cff** [comment]
无效反馈

**Comment by wzgrx** [comment]
后续处理，重新卸载ksu后，重新安装所有模块，重启恢复正常

**Comment by wzgrx** [comment]
> 无效反馈

怎么解决呢，重启还是显示[❌ Stop inject zygote due to crash. Root: KernelSU] Standalone implementation of Zygisk.

**Comment by 5ec1cff** [comment]
ksu 日志发一下

**Comment by wzgrx** [comment]
> ksu 日志发一下

[KernelSU_bugreport_2024-04-08_19_41.tar.gz](https://github.com/Dr-TSNG/ZygiskNext/files/14904915/KernelSU_bugreport_2024-04-08_19_41.tar.gz)

**Comment by wzgrx** [comment]
测试了原版的lsp7058和mod版本72，使用next1.04版本都会出现这种问题，开始卸载lsp和next，重新安装重启后会正常使用，然后再重启一次，又会变成[❌ Stop inject zygote due to crash. Root: KernelSU] Standalone implementation of Zygisk.
重复安装老版本重启无效，必须要卸载重启，重新安装重启才能正常使用，再重启一次又会异常。
手机之前用的是next1.03版本，一切正常，升级1.04后出现这种情况，手机期间没有升级rom，安装模块等其他任何操作

**Comment by wzgrx** [comment]
next1.04关闭lsp模块后显示正常，lsp原版7058和mod版本测试都用不了

**Comment by 5ec1cff** [comment]
不发日志就不要浪费时间了

**Comment by 5ec1cff** [comment]
不好意思，没看清楚
https://modules.lsposed.org/module/dialog.box/ 卸载这个模块

**Comment by wzgrx** [comment]
> 不好意思，没看清楚 https://modules.lsposed.org/module/dialog.box/ 卸载这个模块

好的，我试试，谢谢开发者

**Comment by wzgrx** [comment]
> > 不好意思，没看清楚 https://modules.lsposed.org/module/dialog.box/ 卸载这个模块
> 
> 好的，我试试，谢谢开发者

测试了几次，确实是dia模块的问题，dia模块不能勾选系统框架，勾选了，next会显示错误，取消勾选就正常了，感谢开发者回复。
